### ISSUE TITLE
build failure after pulling the latest code

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#100]
make[3]: Entering directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/quote/linux'
/opt/intel/sgxsdk/bin/x64/sgx_edger8r --untrusted ../enclave/qe3.edl --search-path ../enclave
GEN  =>  qe3_u.c
CC   <=  qe3_u.c
CXX  <=  ../qe_logic.cpp
CXX  <=  ../sgx_ql_core_wrapper.cpp
true
make[4]: Entering directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/pce_wrapper/linux'
make[4]: Leaving directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/pce_wrapper/linux'
g++ qe3_u.o se_thread.o se_trace.o ../qe_logic.o ../sgx_ql_core_wrapper.o -shared -fstack-protector-strong -O2 -D_FORTIFY_SOURCE=2 -UDEBUG -DNDEBUG -ffunction-sections -fdata-sections -Wall -Wextra -Winit-self -Wpointer-arith -Wreturn-type -Waddress -Wsequence-point -Wformat-security -Wmissing-include-dirs -Wfloat-equal -Wundef -Wshadow -Wcast-align -Wconversion -Wredundant-decls -DITT_ARCH_IA64 -g -L/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/build/linux -L/opt/intel/sgxsdk/lib64 -lpthread -ldl  -DDISABLE_TRACE -Wl,--version-script=qe3_logic.lds -Wl,--gc-sections -o libsgx_qe3_logic.so
/usr/bin/ld: se_thread.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: se_thread.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: se_thread.o: unable to initialize decompress status for section .debug_info
/usr/bin/ld: se_thread.o: unable to initialize decompress status for section .debug_info
se_thread.o: file not recognized: File format not recognized
collect2: error: ld returned 1 exit status
Makefile:91: recipe for target 'libsgx_qe3_logic.so' failed
make[3]: *** [libsgx_qe3_logic.so] Error 1
make[3]: Leaving directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/quote/linux'
Makefile:90: recipe for target '../../quote/linux/libsgx_qe3_logic.so' failed
make[2]: *** [../../quote/linux/libsgx_qe3_logic.so] Error 2
make[2]: Leaving directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/ql/linux'
Makefile:55: recipe for target 'qe3_logic' failed
make[1]: *** [qe3_logic] Error 2
make[1]: Leaving directory '/home/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration'
Makefile:39: recipe for target 'QuoteGeneration' failed
make: *** [QuoteGeneration] Error 2

**Comment by llly** [comment]
There is a bug in the clean recipe in Makefile. You can use `git clean -xdf` all ignored files as a workaround..

**Comment by wangsu502** [comment]
> There is a bug in the clean recipe in Makefile. You can use `git clean -xdf` all ignored files as a workaround..

thanks!
and :
$ make
make -C QuoteGeneration
make[1]: Entering directory '/home/leo/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration'
Please run download_prebuilt.sh before compiling
Exiting......
/bin/sh: 1: exit: Illegal number: -2
Makefile:47: recipe for target 'opt_check_failed' failed
make[1]: *** [opt_check_failed] Error 2
make[1]: Leaving directory '/home/leo/sgx/SGXDataCenterAttestationPrimitives/QuoteGeneration'
Makefile:39: recipe for target 'QuoteGeneration' failed
make: *** [QuoteGeneration] Error 2

so why not to execute download_prebuilt.sh automatically in top level Makefile?

**Comment by llly** [comment]
Separating downloading from building helps machine with no/slow internet connection.
You don't need to download prebuilt for each build and you need to redownload prebuilt after major release.
