### ISSUE TITLE
Questions about name libdcap_quoteprov.so.1

### ISSUE THREAD

**Issue by yufjiang** [intel/SGXDataCenterAttestationPrimitives#104]
Installing Intel QPL will have the package libdcap_quoteprov.so.1 installed. I am wondering is there any particular reason that we name the library libdcap_quoteprov.so.1, instead of libdcap_quoteprov.so?

**Comment by hyjiang** [comment]
You can refer to Linux dynamic library naming convention here.
https://tldp.org/HOWTO/Program-Library-HOWTO/shared-libraries.html

**Comment by MWShan** [comment]
libdcap_quoteprov.so.1 is the soname for the library.  It represents version 1 of the API.  The latest version of the developer package for the Quote Provider Library will provide a symbolic link from the linker name libdcap_quoteprov.so to the soname libdcap_quoteprov.so.1.

If you install the developer package.  The package is provided here: https://download.01.org/intel-sgx/sgx-linux/2.11/distro/ubuntu18.04-server/debian_pkgs/devel/libsgx-dcap-default-qpl-dev/
