### ISSUE TITLE
Programmatic way to force DCAP libs to use AESM (similar to "SGX_AESM_ADDR")

### ISSUE THREAD

**Issue by dimakuv** [intel/SGXDataCenterAttestationPrimitives#107]
Currently, the user needs to run an application with `SGX_AESM_ADDR=1 ./my-app` if she wants to force DCAP libraries to use AESM (instead of creating QE and PCE in the same process, which is the default).

I didn't find any API to enforce this (so that the user doesn't need to explicitly specify this env variable).

Even worse, I cannot even do `setenv("SGX_AESM_ADDR", "1", /*overwrite=*/1)` in my program because DCAP libraries look at `SGX_AESM_ADDR` at *initialization/constructor* time:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4605fae1c606de4ff1191719433f77f050f1c33c/QuoteGeneration/quote_wrapper/ql/sgx_dcap_ql_wrapper.cpp#L146-L152.
So by the time I call `setenv()`, there is no guarantee `g_out_of_proc` was not yet set.

It would be great to have an API like `set_aesm_usage(true/false)` or something.

**Comment by dimakuv** [comment]
Ping. Any comments on this?

**Comment by dimakuv** [comment]
@fqiu1 Sorry, I don't understand your suggestion.

I want to use the `sgx_qe_get_quote()` function provided by the DCAP library. This function is a wrapper around `sgx_ql_get_quote()` (in-proc mode) and `get_quote_ex_function()` (out-of-proc mode). The choice of which mode to use is dictated by `SGX_AESM_ADDR` envvar (memorized in the global variable `g_out_of_proc`).

I'm taking about this code: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/5cca11f9ece7be2a55b2aec10deb4b1c016fde3a/QuoteGeneration/quote_wrapper/ql/sgx_dcap_ql_wrapper.cpp#L523-L572

Are you advising me to skip calling into the DCAP libraries and instead call into the SGX SDK/PSW libraries directly? But then is it legal to call some functions in the DCAP libraries, and some functions in the SGX SDK/PSW libraries? What is the point of the DCAP libraries (this github repository) then?

**Comment by fqiu1** [comment]
Yes, SGX SDK/PSW and DCAP are in different github repos. But, if you want to use out-of-proc mode, you need install packages built from SGX SDK/PSW repo, for instance, libsgx-quote-ex, sgx-aesm-servier, libsgx-enclave-common, etc.  I think switching to APIs exposed by libsgx-quote-ex won't introduce more runtime dependencies.

**Comment by dimakuv** [comment]
@fqiu1 Sorry for a naive question: What is the purpose of this DCAP repository then? If quote generation can be done via Intel SGX SDK/PSW libraries, then what is the point of separate DCAP libraries?

**Comment by fqiu1** [comment]
DCAP is designed to provide library interfaces only from the beginning. Then there are some customers require out-of-proc support. So we extended PSW to reuse DCAP libraries and provide quote_ex interfaces. 
BTW, I think there is a workaround for your case: setenv in your application and then use dlopen to load DCAP library

**Comment by dimakuv** [comment]
> Then there are some customers require out-of-proc support. So we extended PSW to reuse DCAP libraries and provide quote_ex interfaces.

That's very good to know! I didn't realize it before. So looks like Gramine can simply use the `quote_ex` interfaces in the PSW libs, and not link against this DCAP library.

> BTW, I think there is a workaround for your case: setenv in your application and then use dlopen to load DCAP library

Yes, this is a possible workaround. Thanks.
