### ISSUE TITLE
build failed 

### ISSUE THREAD

**Issue by zhoushuntong** [intel/SGXDataCenterAttestationPrimitives#108]
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/zip]
Saving to: ‘/usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification/sgxssl/lin_2.5_1.1.1d.zip.1’

lin_2.5_1.1.1d.zip.1                                   [                                                                           <=>                                   ]   2.94M  4.31KB/s    in 11m 28s 

2020-05-09 16:06:57 (4.37 KB/s) - ‘/usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification/sgxssl/lin_2.5_1.1.1d.zip.1’ saved [3078260]

File /usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification/sgxssl//lin_2.5_1.1.1d.zip checksum failure
Makefile:180: recipe for target 'PREPARE_SGX_SSL' failed
make[3]: *** [PREPARE_SGX_SSL] Error 255
make[3]: Leaving directory '/usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification/QvE'
Makefile:37: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification'
Makefile:64: recipe for target 'qve_wrapper' failed
make[1]: *** [qve_wrapper] Error 2
make[1]: Leaving directory '/usr/src/SGXDataCenterAttestationPrimitives/QuoteGeneration'
Makefile:39: recipe for target 'QuoteGeneration' failed
make: *** [QuoteGeneration] Error 2

**Comment by hyjiang** [comment]
From the log below, SgxSSL package you download is corrupt, pls double check. 

``` File /usr/src/SGXDataCenterAttestationPrimitives/QuoteVerification/sgxssl//lin_2.5_1.1.1d.zip checksum failure ```
