### ISSUE TITLE
Error returned from the p_sgx_get_quote_config API. 0xe019

### ISSUE THREAD

**Issue by 60ke** [intel/SGXDataCenterAttestationPrimitives#110]
when i build SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample  and run app

The following information appears:
```shell
/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app 
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

[ecdsa_init_quote ../qe_logic.cpp:1183] Call sgx_pce_get_target().
[ecdsa_init_quote ../qe_logic.cpp:1192] Call Load the QE.
[load_qe ../qe_logic.cpp:622] Call sgx_create_enclave for QE. /usr/lib/x86_64-linux-gnu/libsgx_qe3.signed.so
[ecdsa_init_quote ../qe_logic.cpp:1231] Read ECDSA blob.
[get_qpl_handle ../qe_logic.cpp:247] Found the Quote's dependent library. /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1
[read_persistent_data ../qe_logic.cpp:907] Couldn't find 'sgx_ql_read_persistent_data()' in the platform library. (null)
[ecdsa_init_quote ../qe_logic.cpp:1237] ECDSA Blob doesn't exist is persistent storage.  Try to use the cached version.
[ecdsa_init_quote ../qe_logic.cpp:1263] Invalid ECDSA Blob verificaton. 0xd004, generate a new key.
[ecdsa_init_quote ../qe_logic.cpp:1453] Generate and certify a new ECDSA attestation key
[ecdsa_init_quote ../qe_logic.cpp:1470] Get ATT Key.
[get_qpl_handle ../qe_logic.cpp:247] Found the Quote's dependent library. /usr/lib/x86_64-linux-gnu/libdcap_quoteprov.so.1
[get_platform_quote_cert_data ../qe_logic.cpp:336] Found the sgx_ql_get_quote_config and sgx_ql_free_quote_config API.
[get_platform_quote_cert_data ../qe_logic.cpp:337] Request the Quote Config data.
[get_platform_quote_cert_data ../qe_logic.cpp:340] Error returned from the p_sgx_get_quote_config API. 0xe019
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe019
```

**Comment by hyjiang** [comment]
Pls make sure you have configured PCCS correctly, you can follow PCCS README.
Also, In test env, you need to change to "USE_SECURE_CERT=FALSE" in file /etc/sgx_default_qcnl.conf.

**Comment by 60ke** [comment]
嗯 可以了。之前设置pccs 时目录错了，应该是/opt/intel/sgx-dcap-pccs/config。 第三方远程证实只是在intel和程序直接做了一个中间服务吗？(第三方远程证实，最终也是需要和intel交互的吗？)

**Comment by hyjiang** [comment]
ECDSA Remote attestation is NOT an intermediate service. it needs PCCS/PCS just because attestation key is signed by Intel PCK, then you need some verification collateral (corresponding PCK cert, CRL, signing chain and etc) to verify the PCK signature & cert's integrity and freshness.

You can review high level Arch from https://download.01.org/intel-sgx/dcap-1.1/linux/docs/Intel_SGX_DCAP_ECDSA_Orientation.pdf

Also pls help to close this issue if no other issue.

**Comment by 60ke** [comment]
thanks first  . the PCK must signed by Intel?  can i completely divorced intel when i run The third party attention?

**Comment by hyjiang** [comment]
PCK must be signed by Intel.
You can always to use your own key for sure, but it means your cannot get benefit from SGX.

**Comment by 60ke** [comment]
thanks。

**Comment by TY-cc** [comment]
hi, How to you solve this error？ i have change the file /etc/sgx_default_qcnl.conf.

**Comment by 60ke** [comment]
> hi, How to you solve this error？ i have change the file /etc/sgx_default_qcnl.conf.

use this : https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/110#issuecomment-631818078

**Comment by TY-cc** [comment]
可以加个微信么。Cch_1015
