### ISSUE TITLE
Ubuntu 18.04, install of sgx_linux_x64_driver_1.35.bin silently fails

### ISSUE THREAD

**Issue by nrgifford** [intel/SGXDataCenterAttestationPrimitives#124]
Is installing the 1.35 SGX driver with Ubuntu 18.04 and Kernel 4.15 a supported configuration?

Ubuntu 18.04, Kernel 4.15
Intel SGX Driver 1.20 is installed.

When I attempt to install 1.35 SGX driver, the installation fails with no error message.
Intel SGX Driver 1.20 is still installed.
OE Sample application helloworld now fails.

./host/helloworld_host ./enclave/enclave.signed
2020-08-03T22:54:23.000000Z [(H)ERROR] tid(0x7f952ffeeb80) | enclave_create with ENCLAVE_TYPE_SGX1 type failed (err=0x1) (oe_result_t=OE_PLATFORM_ERROR) [/source/host/sgx/sgxload.c:oe_sgx_create_enclave:480]
2020-08-03T22:54:23.000000Z [(H)ERROR] tid(0x7f952ffeeb80) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_sgx_build_enclave:812]
2020-08-03T22:54:23.000000Z [(H)ERROR] tid(0x7f952ffeeb80) | :OE_PLATFORM_ERROR [/source/host/sgx/create.c:oe_create_enclave:960]
oe_create_helloworld_enclave(): result=21 (OE_PLATFORM_ERROR)

**Rebooting doesn't resolve the failure.**

The issue is fixed after
sudo apt update
sudo apt upgrade

SGX driver is still at 1.20.

**Comment by haitaohuang** [comment]
Not sure why it went silent. Is the regular Ubuntu image or cloud flavor (e.g. Azure flavor)?

4.15 kernel is supported. Did you try to uninstall old driver before installing new one?

**Comment by nrgifford** [comment]
It’s a regular Ubuntu image.
I think the problem is that I can’t get the v1.20 driver to uninstall.

 I uninstalled the PSW and all SGX components first.

sudo /opt/intel/sgxdriver/uninstall.sh

Uninstall failed because the kernel module is in use

modinfo intel_sgx
filename:       /lib/modules/4.15.0-112-generic/updates/dkms/intel_sgx.ko
version:        1.20
license:        Dual BSD/GPL
author:         Jarkko Sakkinen <jarkko.sakkinen@linux.intel.com>
description:    Intel SGX Driver
srcversion:     AA38F3484C7F0D7582A954D
alias:          acpi*:INT0E0C:*
depends:
retpoline:      Y
name:           intel_sgx
vermagic:       4.15.0-112-generic SMP mod_unload
signat:         PKCS#7
signer:
sig_key:
sig_hashalgo:   md4

lsmod | grep intel_sgx
intel_sgx              45056  0

**Comment by haitaohuang** [comment]
You need stop AESM before uninstalling driver. But uninstalling PSW usually does that. You might have something else using it.
Try use "lsof | grep sgx" to see if running process is using /dev/sgx*.

**Comment by nrgifford** [comment]
I was finally able to get the driver removed and the v1.35 driver installed.

I don’t know what the issue was, but it’s fixed now.

Thanks.
