### ISSUE TITLE
ERROR: could not insert 'intel_sgx': No such device

### ISSUE THREAD

**Issue by markueni** [intel/SGXDataCenterAttestationPrimitives#128]
Hei,

I am trying to install SGXDCP driver but when I execute the following command
`/sbin/modprobe intel_sgx` I got the following error
`modprobe: ERROR: could not insert 'intel_sgx': No such device`
I am able though to install the isgx driver from binary files but I want to use the out-of-tree driver. I have enabled SGX in my Bios and also disabled Secure Boot. Also when I try to install SGXDCAP driver I of course un install first the sgx-driver (isgx).

Is there any reason why I am not able to install such driver and what should I do?

**Comment by haitaohuang** [comment]
DCAP driver needs FLC. Please ensure u have this when running "cpuid | grep -i sgx":
 
SGX_LC: SGX launch config supported      = true

**Comment by markueni** [comment]
@haitaohuang  It seems that my cpu does not support it. 
```
   SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
      SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = false
   SGX capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
   SGX attributes (0x12/1):
```
Ok lets forget about DCAP drivers. Even when I install isgx the problem is that I can not run SampleCode applications. It says that `there is no sgx device, make sure to enable SGX in Bios and then install sgx-driver`. The problem is that I have the isgx driver and in my BIOS I have enabled SGX so do not know why this problem is still happening. I have another computer with the same cpu and processor and in this other computer works ok. The only thing which comes in my mind that what may be wronng is the kernel version: I have 5.4 kernel version. In the other computer where SampleCodes are executed I have 5.0.3 kernel. Is there a problem with this kernel? I tried to find Intel patches for this kernel but could not find them.

**Comment by haitaohuang** [comment]
it could be the kernel. We only test and support limited versions of distro/kernel combinations for isgx. See README in that repo.

**Comment by haitaohuang** [comment]
I'm closing this issue as original concern is addressed
