### ISSUE TITLE
Got an error 0xe001 when executing QuoteGenerationSample

### ISSUE THREAD

**Issue by Liaojinghui** [intel/SGXDataCenterAttestationPrimitives#15]
I got an error of 0xe001 when I run ./App of QuoteGeneration Sample

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe001

I can't find any document referring to this error code.

**Comment by llly** [comment]
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/5685c0072b4596863a0f0401f9f570b083e7a745/QuoteGeneration/psw/quote_wrapper/common/inc/sgx_ql_lib_common.h#L50 
It's unexpected error, comes from unhanded error code. Cnould you please build  debug binary with `DEBUG=1` and install then run again? More detailed log will be printed.

**Comment by chao-novovivo** [comment]
Also, get the same error of Oxe001.
------------ error --------------- 
This step is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!
Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe001
------------- Solutions -----------------
Solution1: Make with DEBUG = 1, no information output.
Solustion2: Changing the function defined in /quote_wrapper/ql/sgx_dcap_ql_wrapper.cpp. Could not cout anything.
Any advice for debugging.Thanks

**Comment by jdbeaney** [comment]
Typically, this error can occur if you have not installed the DCAP driver.  In DCAP 1.2, I believe you will get a more descriptive error in this case.  Are you running with DCAP 1.1 or DCAP 1.2?  Can you attach the trace log you got when you built and ran with DEBUG=1?

**Comment by chao-novovivo** [comment]
Hi,
Thanks for your prompt response. I am using DCAP 1.1. By the way, where could I find the trace log file or should I set the file path in any file? Thanks for your time.
Best,

**Comment by jdbeaney** [comment]
The tracing (when building with DEBUG=1) is implemented in the https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/common/src/se_trace.c and the output will be in stdout or stderr based on the traces debug level.
