### ISSUE TITLE
Error: Unable to retrieve the collateral from the Intel SGX PCS

### ISSUE THREAD

**Issue by hustliyilin** [intel/SGXDataCenterAttestationPrimitives#153]
I refer to [this guide](https://software.intel.com/content/www/us/en/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html) to subscribe to the Intel PCS and set up the Intel PCCS. However, when I run pccs typing this command

```shell
node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
```

and there is an error like
```shell
# node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
2020-12-24 17:29:16.015 [info]: HTTPS Server is running on: https://localhost:8081
2020-12-24 17:29:23.337 [info]: Request-ID is : cca33f9e55bc4d21be1ad4f02eb6bd12
2020-12-24 17:29:23.338 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:70:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

and I run QuoteGenerationSample with error code 0xe044
```shell
# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044
```

Could you help me? Thanks a lot

**Comment by hyjiang** [comment]
What type of system are you using?

From the info you provided, seems you are using a pre-production system, which doesn't have a production silicon. 
In this case, pls use [SBX service](https://sbx.api.portal.trustedservices.intel.com/) and corresponding API key to get PCK cert. 

```But pls note that pre-production system is only for trial/development usage, you should NOT use it in PRODUCT environment```

**Comment by hustliyilin** [comment]
> What type of system are you using?
> 
> From the info you provided, seems you are using a pre-production system, which doesn't have a production silicon.
> In this case, pls use [SBX service](https://sbx.api.portal.trustedservices.intel.com/) and corresponding API key to get PCK cert.
> 
> `But pls note that pre-production system is only for trial/development usage, you should NOT use it in PRODUCT environment`

Thanks a lot, I will use the SBX service to get PCK cert.

**Comment by hustliyilin** [comment]
> What type of system are you using?
> 
> From the info you provided, seems you are using a pre-production system, which doesn't have a production silicon.
> In this case, pls use [SBX service](https://sbx.api.portal.trustedservices.intel.com/) and corresponding API key to get PCK cert.
> 
> `But pls note that pre-production system is only for trial/development usage, you should NOT use it in PRODUCT environment`

After using the [SBX service](https://sbx.api.portal.trustedservices.intel.com/) you provided,  the error that Unable to retrieve the collateral from the Intel SGX PCS is solved.

However, there is a new error that `The platform was not found in the cache` when I type the same command

```shell
# /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
2020-12-28 11:13:31.597 [info]: HTTPS Server is running on: https://localhost:8081
2020-12-28 11:13:41.998 [error]: Error: The platform was not found in the cache.
    at Proxy.getPckCert (/opt/intel/sgx-dcap-pccs/services/pckcertService.js:308:15)
    at async getPckCert (/opt/intel/sgx-dcap-pccs/controllers/pckcertController.js:71:25)
2020-12-28 11:13:42.001 [info]: 127.0.0.1 - - [28/Dec/2020:03:13:42 +0000] "GET /sgx/certification/v3/pckcert?qeid=A69D601F3CC05F4A42AA86558E394D10&encrypted_ppid=B686FC11E16E6B3A223661A7900A8F69C79181011E019E2670C11E5074632F7E0B12B09EA11175E2790AEDBE4E4082D06FC2EC137918994C6FF968BFC1F49705A6C5CA22603EC76DD54ED1B529D48ADAB88BFFC9FB2E6CF4331C1ABADCADC6EEEB56C88FBE2E1197D675FD81A17019BC9B9F32F91959C8092D94D345B89FE73FFD5FE44827C6CE9CDE2B37281063A5A135E429985F32AF1587E6F58C7AEB819EB8416A3F7722E417E411AE7516BD6DC074D8B748F881E9CBC5D2A099AB014A55FA17295A7A9EAE66BB0E0A850B0E2029DDB3972D4669FC2C634197F2BCF75C5E365DF1DCF25B14ED498FCED24CBA05174394D84CBDD3299C2BC13B7E7D09C2B1E4BD63107930A510417B437B365241C5FF16BD0E3E5B26FD752C654E3355AD64607770F663A479C44333D1A11A7CE1384A90B801AC12D45B96DFCEF82F1F2A3C2B6F58C3D0EC16B25242FE766356DC21F39A136FF64C3CE72FDFBAFF854DBA48A8F8DF0F53CD990DA9B6D29360418E2E6FBECAAB0B402118E0908E826F284333&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000 HTTP/1.1" 461 40 "-" "-"
```

 And I run QuoteGenerationSample with error code `0xe047`

```shell
# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe047
```

How can I solve the new problem? Thanks a lot.

**Comment by hyjiang** [comment]
Maybe you can try to clean the DB file in cache server, then try again.

**Comment by lingyuj** [comment]
Which caching mode did you set in your config file? Can you try "LAZY" mode?

**Comment by hustliyilin** [comment]
> Which caching mode did you set in your config file? Can you try "LAZY" mode?

I set the `REQ` mode in my config file. When I change the mode to `LAZY`,  the error is same as `Unable to retrieve the collateral from the Intel SGX PCS`.

**Comment by hustliyilin** [comment]
> Maybe you can try to clean the DB file in cache server, then try again.

Thanks for your suggestion. But when I remove the `/opt/intel/sgx-dcap-pccs/pckcache.db` file and try again. The error that `The platform was not found in the cache` still exists.

**Comment by lingyuj** [comment]
Did the error log change? After you change the mode to LAZY, can you try below command?
curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"

**Comment by hyjiang** [comment]
In fact, I can use the encrypted PPID and other info to get collateral from SBX server.
So it means the platform & SGX SW status are correct, I suppose you need to check PCCS configuration, also pls make sure you also applied API key for SBX server.

**Comment by hustliyilin** [comment]
> Did the error log change? After you change the mode to LAZY, can you try below command?
> curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"

Thanks for your suggestion. When I change the mode to `LAZY`,  start the pccs server and type the `curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"` command, the client log is below

```shell
# curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl"
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8081 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8081 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, [no content] (0):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN, server accepted to use http/1.1
* Server certificate:
*  subject: C=CN; ST=ZheJiang; L=HangZhou; O=test; OU=test; CN=test; emailAddress=jingshui1037@163.com
*  start date: Dec 28 06:15:44 2020 GMT
*  expire date: Dec 28 06:15:44 2021 GMT
*  issuer: C=CN; ST=ZheJiang; L=HangZhou; O=test; OU=test; CN=test; emailAddress=jingshui1037@163.com
*  SSL certificate verify result: self signed certificate (18), continuing anyway.
* TLSv1.3 (OUT), TLS app data, [no content] (0):
> GET /sgx/certification/v3/rootcacrl HTTP/1.1
> Host: localhost:8081
> User-Agent: curl/7.61.1
> Accept: */*
>
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, [no content] (0):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS app data, [no content] (0):
< HTTP/1.1 200 OK
< X-Powered-By: Express
< Content-Type: application/octet-stream
< Content-Length: 586
< ETag: W/"24a-nYdPKgsUoUFjxwAGeMpSFvT40dI"
< Date: Mon, 28 Dec 2020 06:17:27 GMT
< Connection: keep-alive
< Keep-Alive: timeout=5
<
* Connection #0 to host localhost left intact
308201213081c8020101300a06082a8648ce3d0403023068311a301806035504030c11496e74656c2053475820526f6f74204341311a3018060355040a0c11496e74656c20436f72706f726174696f6e3114301206035504070c0b53616e746120436c617261310b300906035504080c024341310b3009060355040613025553170d3230303532313036333733335a170d3231303532313036333733335aa02f302d300a0603551d140403020101301f0603551d2304183016801422650cd65a9d3489f383b49552bf501b392706ac300a06082a8648ce3d04030203480030450220279e4ddb5c5b979074fdc676788775a65ca5d8b18c33db08dd2ca2a965519356022100bbcee14ab1e78a19181929c3317683eef30561647b482eb67826b3e503aa797a
```

and the pccs server log is 

```shell
# /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
2020-12-28 14:17:19.013 [info]: HTTPS Server is running on: https://localhost:8081
2020-12-28 14:17:27.031 [info]: 127.0.0.1 - - [28/Dec/2020:06:17:27 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 200 586 "-" "curl/7.61.1"

```

Does the log seem OK? 

And when I retry  QuoteGenerationSample again, the error is

```shell
# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe044
```

the corresponding pccs server log is 

```shell
# /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js
morgan deprecated default format: use combined format node_modules/esm/esm.js:1:278827
2020-12-28 14:17:19.013 [info]: HTTPS Server is running on: https://localhost:8081
2020-12-28 14:17:27.031 [info]: 127.0.0.1 - - [28/Dec/2020:06:17:27 +0000] "GET /sgx/certification/v3/rootcacrl HTTP/1.1" 200 586 "-" "curl/7.61.1"

2020-12-28 14:23:40.573 [info]: Request-ID is : 015ac4864c884765b4299e75bd088760
2020-12-28 14:23:40.573 [error]: Error: Unable to retrieve the collateral from the Intel SGX PCS.
    at do_request (/opt/intel/sgx-dcap-pccs/pcs_client/pcs_client.js:70:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-12-28 14:23:40.574 [info]: 127.0.0.1 - - [28/Dec/2020:06:23:40 +0000] "GET /sgx/certification/v3/pckcert?qeid=A69D601F3CC05F4A42AA86558E394D10&encrypted_ppid=192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000 HTTP/1.1" 504 57 "-" "-"
```

**Comment by lingyuj** [comment]
So it looks like your platform is not in the server database. Maybe you need to flash BIOS?

**Comment by hustliyilin** [comment]
> So it looks like your platform is not in the server database. Maybe you need to flash BIOS?

Thanks a lot, I will try it.

**Comment by hyjiang** [comment]
As I said, the platform and SGX SW status are correct, I can use the info you provided to retrieve corresponding collateral info.
So pls check you are using correct backend service and correct API key.

```
curl -v GET https://sbx.api.trustedservices.intel.com/sgx/cncrypted_ppid="192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000"  -H "Ocp-Apim-Subscription-Key: xxxxxx"
```

**Comment by lingyuj** [comment]
> As I said, the platform and SGX SW status are correct, I can use the info you provided to retrieve corresponding collateral info.
> So pls check you are using correct backend service and correct API key.
> 
> ```
> curl -v GET https://sbx.api.trustedservices.intel.com/sgx/cncrypted_ppid="192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000"  -H "Ocp-Apim-Subscription-Key: xxxxxx"
> ```

You are correct :)

**Comment by hustliyilin** [comment]
> So pls check you are using correct backend service and correct API key.

Thanks a lot.

**Comment by hustliyilin** [comment]
> As I said, the platform and SGX SW status are correct, I can use the info you provided to retrieve corresponding collateral info.
> So pls check you are using correct backend service and correct API key.
> 
> ```
> curl -v GET https://sbx.api.trustedservices.intel.com/sgx/cncrypted_ppid="192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000"  -H "Ocp-Apim-Subscription-Key: xxxxxx"
> ```

Is this command correct? I use this command with my API key, there is an error that URL is invalid like this

```shell
...
< HTTP/1.1 400 Bad Request
< Content-Type: text/html; charset=us-ascii
< Date: Mon, 28 Dec 2020 09:39:12 GMT
< Connection: close
< Content-Length: 324
<
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
* Closing connection 1
* TLSv1.2 (OUT), TLS alert, close notify (256):
```

**Comment by hustliyilin** [comment]
> As I said, the platform and SGX SW status are correct, I can use the info you provided to retrieve corresponding collateral info.
> So pls check you are using correct backend service and correct API key.
> 
> ```
> curl -v GET https://sbx.api.trustedservices.intel.com/sgx/cncrypted_ppid="192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000"  -H "Ocp-Apim-Subscription-Key: xxxxxx"
> ```

Thanks a lot. Could you delete the command please?  Beasuse it is unsafe for me to expose my encrypted_ppid. I already delete my encrypted_ppid in this issue.

**Comment by hyjiang** [comment]
Sure, just deleted it. 
Pls note that it's the info is encrypted, only Intel backend service can decrypt it. So it's not sensitive data.

**Comment by hustliyilin** [comment]
> Sure, just deleted it.
> Pls note that it's the info is encrypted, only Intel backend service can decrypt it. So it's not sensitive data.

Thanks a lot.

**Comment by hustliyilin** [comment]
> > As I said, the platform and SGX SW status are correct, I can use the info you provided to retrieve corresponding collateral info.
> > So pls check you are using correct backend service and correct API key.
> > ```
> > curl -v GET https://sbx.api.trustedservices.intel.com/sgx/cncrypted_ppid="192D955CCC597574DC39848E83F960E01B5CCD98D9ECE4BF3FD8D94B0E67A5631DCF3CABFDFFA141F08FF8A47F2A5F767FC79E8595CBE853475C549FAB3300DCAF13B6E0BB3807F61C08104917B9EE2DCE5F05B414D0E4387880DFFB2985F0EA3F4BAA14B84D5F17DDFD9858FB241310EFE4423A5894D3545CB216D33E33AFB7BF953310CC0BBB845526A1EA330043C1262794E0C1C132A1DC47024D78E05AA9C80C60037C89AEE3B108DACE616EB2F71A03E05E87059C8CA681DC3E8C96704A57CC0FBB367D49FD18161EF791AEDF82839F6631AF08158D15E0878B27AB0D343A0CE29ABA27C1D9D97AA6A9FFAD9F4038F61F23EFBFCF2E9432284AE2DF39A502CF9CFDEB835DE8880E9DC729E35199036A9E5C95CDCE4EB8DCE66E938A8197A375B6C371A6D58EA913D91FECABBE403C311FDD8CE86DA6B150426AEB107F8BC78E665FEF4CB4C99EC9D07C290241EF2745C53E87FB31F6D92DB8527CF96D375644E051D4CFE183DC7BB4548B706B82EE17433285AB7D90468E1969D494B748&cpusvn=0303FFFF00FF00000000000000000000&pcesvn=0A00&pceid=0000"  -H "Ocp-Apim-Subscription-Key: xxxxxx"
> > ```
> 
> You are correct :)

Thanks a lot. Could you delete the command please? Beasuse it is unsafe for me to expose my encrypted_ppid. I already delete my encrypted_ppid in this issue.

**Comment by hustliyilin** [comment]
> Sure, just deleted it.
> Pls note that it's the info is encrypted, only Intel backend service can decrypt it. So it's not sensitive dat


Thanks a lot. I succeed to run the QuoteGenerationSample, It is true that my API key is incorrect. The log is

```shell
./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:succeed!
Step2: Call create_app_report:succeed!
Step3: Call sgx_qe_get_quote_size:succeed!
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
sgx_qe_cleanup_by_policy is valid in in-proc mode only.

 Clean up the enclave load policy:succeed!
```

**Comment by lingyuj** [comment]
> Thanks a lot. Could you delete the command please? Beasuse it is unsafe for me to expose my encrypted_ppid. I already delete my encrypted_ppid in this issue.

Done. You need to delete your own reply that quotes the enc-ppid .

**Comment by hustliyilin** [comment]
> > Thanks a lot. Could you delete the command please? Beasuse it is unsafe for me to expose my encrypted_ppid. I already delete my encrypted_ppid in this issue.
> 
> Done. You need to delete your own reply that quotes the enc-ppid .

Done, thanks again. I close this issue now.

**Comment by veenasai2** [comment]
Hi, 

I followed all the above troubleshooting steps, but still I am facing the same error "Unable to retrieve the collateral from the Intel SGX PCS". Few more details:

1. I am using "uri": "https://sbx.api.trustedservices.intel.com/sgx/certification/v3/", as part of /opt/intel/sgx-dcap-pccs/config/default.json.  
2. I have subscribed to Product SBX Intel® Software Guard Extensions Provisioning Certification Service and I am using the generated API key.
3. PCCS service is running fine in LAZY caching mode.
4. BIOS is updated.
5. curl -v -k -G "https://localhost:8081/sgx/certification/v3/rootcacrl is successful


@hustliyilin "my machine needs SBX service": how did you register your pre-prod system to sbx.api.trustedservices.intel.comsbx.api.trustedservices.intel.com?

Did you use the below command or any other method?
curl -H "Content-Type: application/octet-stream" -v --data-binary @platform_manifest -X POST "https://sbx.api.trustedservices.intel.com/sgx/registration/v1/platform"

if you use the above command, then how did you retrieve the platform_manifest binary?

Thank you.

**Comment by hustliyilin** [comment]
> @hustliyilin "my machine needs SBX service": how did you register your pre-prod system to sbx.api.trustedservices.intel.comsbx.api.trustedservices.intel.com?

Thank you for your question, this question is a bit difficult for me, because I am not clear about the registration process of platfrom manifest and my sbx system is registered by someone else.

But I can give you some directions to help you locate and think about the problem:

1. You need to apply for a  [SBX API key](https://sbx.api.portal.trustedservices.intel.com). The SBX API key isn't a product API key but a pre-product API key.
2. You can set the `loglevel` as `debug` in the `/opt/intel/sgx-dcap-pccs/config/default.json` to see more logs.
3. You need to set `USE_SECURE_CERT=FALSE` in `/etc/sgx_default_qcnl.conf` according to [this guide](https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs#local-service-vs-remote-service).
4. You can use the command `curl -v -X GET "https://sbx.api.trustedservices.intel.com/sgx/certification/v1/pckcert?encrypted_ppid=@encrypted_ppid&cpusvn=@cpusvn&pcesvn=@pcesvn&pceid=@pceid" -H "Ocp-Apim-Subscription-Key:@SBX_API_KEY"` to check the key and SBX system is ok or not. As for the  `encrypted_ppid`, `cpusvn`, `pcesvn`, and `pceid`, you can run `/usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js` and the DCAP QuoteGenerationSample to retrieve.

**Comment by veenasai2** [comment]
@hustliyilin Thank you so much for your quick reply. I already followed all the steps that you listed except step2 :) . 

After enabling the debug logs , I can see the "Response code 404 (Not Found)" that means the platform manifest is not available at the sbx service backend (https://sbx.api.portal.trustedservices.intel.com/documentation#register-platform). 

I have requested a support from SBX team. Link: https://community.intel.com/t5/Intel-Software-Guard-Extensions/How-to-retrieve-platform-manifest-from-my-pre-production-server/m-p/1267313/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufEtNTkU1VUo2WUFIR1RSfDEyNjczMTN8U1VCU0NSSVBUSU9OU3xoSw#M4406  (if useful for someone)

**Comment by dabaizzt** [comment]
> @hustliyilin Thank you so much for your quick reply. I already followed all the steps that you listed except step2 :) .
> 
> After enabling the debug logs , I can see the "Response code 404 (Not Found)" that means the platform manifest is not available at the sbx service backend (https://sbx.api.portal.trustedservices.intel.com/documentation#register-platform).
Hello，Have you solved the problem? Now I have the same problem as you. Could you please share with me the solution? Thank you very much～

**Comment by veenasai2** [comment]
Hi @dabaizzt ,

For Pre-production system I did not get a chance to try again. For production systems , I followed this guide : https://software.intel.com/content/www/cn/zh/develop/articles/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html. 
Thank You.

**Comment by TY-cc** [comment]
I sure mu API key is correct. But when i use "curl -v -X GET "https://sbx.api.trustedservices.intel.com/sgx/certification/v1/pckcert?encrypted_ppid=@encrypted_ppid&cpusvn=@cpusvn&pcesvn=@pcesvn&pceid=@pceid" -H "Ocp-Apim-Subscription-Key:@SBX_API_KEY"", it tell me deny my Key

**Comment by lingyuj** [comment]
I see you are using /v1/, why not use /v3/ ?

**Comment by lingyuj** [comment]
> I sure mu API key is correct. But when i use "curl -v -X GET "https://sbx.api.trustedservices.intel.com/sgx/certification/v1/pckcert?encrypted_ppid=@encrypted_ppid&cpusvn=@cpusvn&pcesvn=@pcesvn&pceid=@pceid" -H "Ocp-Apim-Subscription-Key:@SBX_API_KEY"", it tell me deny my Key

To use the sandbox server (aka sbx.api.***), you need the API key for sandbox.
