### ISSUE TITLE
could not insert 'intel_sgx'

### ISSUE THREAD

**Issue by davidgith** [intel/SGXDataCenterAttestationPrimitives#160]
Hi,
I wanted to install the driver and everything works until the last step "sudo /sbin/modprobe intel_sgx".
This result in the error "modprobe: ERROR: could not insert 'intel_sgx': No such device"
I think, my processor i7-8750H should support FLC, am I right? Does anyone have the same problem?
Thanks!

**Comment by llly** [comment]
I think your platform doesn't support FLC.
I tried to install DCAP driver on non-FLC machine and got same error `insmod: ERROR: could not insert module intel_sgx.ko: No such device`

**Comment by lingyuj** [comment]
According to this issue : https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/35
i7-8750H does support FLC. I think you need to check your BIOS or ask your vendor to confirm.

**Comment by davidgith** [comment]
I also found this post, which makes me optimistic... Secure Boot is disabled, SGX is enabled. SGX already worked with the older drivers (until my last experiments), but now I wanted to try it with the DCAP driver with the update for the new kernel, that's obviously not working.

**Comment by lzha101** [comment]
@davidgith what does the 'older drivers' mean? OOT driver or the DCAP driver in previous release? 
And could you please provide more info about the code base you are using and the platform, OS version, kernel version, etc? It may help us to identify the issue.

**Comment by davidgith** [comment]
Maybe "old" was the wrong word. I was able to work with the [linux-sgx-driver](https://github.com/intel/linux-sgx-driver) and I thought, the DCAP driver are better, I don't have much experience, so I want to try to install them again. 
But most of the time, I work with the newest versions of the drivers. I use this [sdk](https://github.com/intel/linux-sgx) but if I'm right, my error with the driver is independent of further work because I already can't install it. I use Ubuntu 20.10 with kernel 5.8.0-41-generic. Is there more helpful information?

**Comment by haitaohuang** [comment]
did you uninstall legacy driver (linux-sgx-driver) before installing DCAP? Also we have an issue on ubuntu 5.8 kernel, and only added support back recently in tip. U may want to try to clone code and build and install following instructions in driver README.

**Comment by davidgith** [comment]
Now I've uninstalled  the driver, but unfortunately nothing changes.
Do you mean this [Readme](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/README.md)? I already followed these steps with make and dkms. This looks good until the modprobe step.

**Comment by haitaohuang** [comment]
can u share output of "cpuid -1 | grep -i sgx"?

**Comment by davidgith** [comment]
The output is:
SGX: Software Guard Extensions supported = true
      SGX_LC: SGX launch config supported      = true
   Software Guard Extensions (SGX) capability (0x12/0):
      SGX1 supported                         = true
      SGX2 supported                         = false
      SGX ENCLV E*VIRTCHILD, ESETCONTEXT     = false
      SGX ENCLS ETRACKC, ERDINFO, ELDBC, ELDUC = false
   SGX attributes (0x12/1):

Does this say something about compatibility to the DCAP driver?

**Comment by haitaohuang** [comment]
it should work, now I really run out of ideas other than re-confirm the steps and clean env: Are you sure you uninstalled the other driver? Do you see any thing "ls /dev/*sgx*"? 
And make sure you have clean build too.

**Comment by davidgith** [comment]
Again, I followed the instructions to delete the driver, I think, it looks good. One problem was, I had different versions of the DCAP driver, but now the installation in dkms looks good.
I don't have the directory sgx in dev.
What do you mean with clean env and clean build? I pulled again, executed make clean and make, copied the whole folder in usr/src/sgx-1.41 and added, built and installed it again. Do I have to do something else?

**Comment by haitaohuang** [comment]
Do you see any error/warning in kernel message when modprobe fails?

**Comment by davidgith** [comment]
If I execute "sudo /sbin/modprobe intel_sgx", I just get the error "modprobe: ERROR: could not insert 'intel_sgx': No such device"
If it helps, "dkms status" prints "sgx, 1.41, 5.8.0-41-generic, x86_64: installed" So I think dkms works...

**Comment by haitaohuang** [comment]
does "dmesg | grep -i sgx" show anything?

**Comment by CitadelCore** [comment]
I'm getting this too, in dmesg:
"intel_sgx: Locked launch policy not supported"

Hardware: Lenovo ThinkPad X1 Tablet, i7-8550U

**Comment by davidgith** [comment]
> does "dmesg | grep -i sgx" show anything?

I get the following:

[    3.829428] intel_sgx: loading out-of-tree module taints kernel.
[    3.829450] intel_sgx: module verification failed: signature and/or required key missing - tainting kernel
[    3.829688] intel_sgx: Locked launch policy not supported
[    3.894618] intel_sgx: Locked launch policy not supported


I guess it's not good if it says something with out-of-tree driver?
The lock launch line comes with every execution of modprobe.

**Comment by CitadelCore** [comment]
I'm pretty sure it's because the launch policy MSRs are set to Locked. Therefore FLC can't be used (?).

Waiting on @haitohuang to confirm.

**Comment by haitaohuang** [comment]
@CitadelCore yes. Usually if BIOS support, there is an entry like SGXPUBKEYHASHMSR_WRITABLE, you set it to enabled.

**Comment by davidgith** [comment]
Hm, if I don't have such a setting, I'm afraid, I don't have FLC support... What a pity.

**Comment by CitadelCore** [comment]
> Hm, if I don't have such a setting, I'm afraid, I don't have FLC support... What a pity.

You can use the driver that I linked above. Worked fine for me.

**Comment by davidgith** [comment]
Thanks for your advise, I have already used them. I just hoped, I also could use the better ones. But then, I will work with the OOT drivers again.

**Comment by haitaohuang** [comment]
your CPUID does show LC capable. Check with your vendor to see if any BIOS update

**Comment by davidgith** [comment]
Hm... I just recognized, my last BIOS update obviously didn't work. But the error is still the same... I uninstalled and installed the driver and restarted my PC a few times, unfortunately without any effect...

**Comment by muhammad-usama-sardar** [comment]
> To check if BIOS configured correctly, "cpuid -1 | grep -i sgx", should show SGX leaves and Launch Control (FLC)

@haitaohuang What exactly would the output `SGX_LC: SGX launch config supported = false` mean? Does it mean that BIOS is not correctly configured? VS. platform doesn't support FLC?

**Comment by haitaohuang** [comment]
BIOS controls IA32_FEATURE_CONTROL MSR bit 17 which  controls the permissions on the IA32_SGXLEPUBKEYHASH MSRs. "SGX_LC: SGX launch config supported = false" means  CPUID.(EAX=07H,
ECX=0H): ECX[30] = 0, i.e., cpu does not support SGX LC.
