### ISSUE TITLE
sgx_qve_verify_quote failed for v3 collateral

### ISSUE THREAD

**Issue by sammyne** [intel/SGXDataCenterAttestationPrimitives#161]
## Env
- DCAP=1.9.100.3
- SDK=2.12.100.3

Libs as 
```bash
ls /usr/lib/x86_64-linux-gnu/ | grep sgx

libsgx_dcap_ql.so.1
libsgx_dcap_ql.so.1.9.100.3
libsgx_dcap_quoteverify.so
libsgx_dcap_quoteverify.so.1
libsgx_dcap_quoteverify.so.1.9.100.3
libsgx_default_qcnl_wrapper.so.1
libsgx_default_qcnl_wrapper.so.1.9.100.3
libsgx_enclave_common.so.1
libsgx_enclave_common.so.1.0.113.3
libsgx_launch.so.1
libsgx_launch.so.1.0.108.3
libsgx_pce.signed.so
libsgx_pce_logic.so
libsgx_qe3.signed.so
libsgx_qe3_logic.so
libsgx_qve.signed.so
libsgx_urts.so
libsgx_urts.so.1
libsgx_urts.so.1.1.110.3
```

## Problem
Quote verification failed on the following line

https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/70f54dba09934381fad79bfe857f172e47819fc7/QuoteVerification/QvE/Enclave/qve.cpp#L1248

exactly at 
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/70f54dba09934381fad79bfe857f172e47819fc7/QuoteVerification/QvE/Enclave/qve.cpp#L1160

Also, it seems the encoding of CRL has been switched from PEM to DER.

Really appreciate if someone could help me figure out the cause of the failure~

**Comment by hyjiang** [comment]
Yes, CRL has changed to DER format.
In quote verification, are you using Intel provided QPL/PCCS or collect the collateral by yourself?

**Comment by sammyne** [comment]
> Yes, CRL has changed to DER format.
> In quote verification, are you using Intel provided QPL/PCCS or collect the collateral by yourself?

I'm using the PCCS implemented myself, but QPL comes from Intel.
So encode CRL in PEM would solve the problem, right? @hyjiang

**Comment by hyjiang** [comment]
> > Yes, CRL has changed to DER format.
> > In quote verification, are you using Intel provided QPL/PCCS or collect the collateral by yourself?
> 
> I'm using the PCCS implemented myself, but QPL comes from Intel.
> So encode CRL in PEM would solve the problem, right? @hyjiang

Pls try to convert the DER format raw data to hex string before passing to QPL.
