### ISSUE TITLE
Install pccs problem

### ISSUE THREAD

**Issue by ltinerary** [intel/SGXDataCenterAttestationPrimitives#172]
I was download sgx-dcap-pccs follow this url [https://download.01.org/intel-sgx/sgx-dcap/1.10/linux/tools/SGXCertRetrievalTool/ubuntu18.04-server/debian_pkgs/web/sgx-dcap-pccs/sgx-dcap-pccs_1.10.100.4-bionic1_amd64.deb](https://download.01.org/intel-sgx/sgx-dcap/1.10/linux/tools/SGXCertRetrievalTool/ubuntu18.04-server/debian_pkgs/web/sgx-dcap-pccs/sgx-dcap-pccs_1.10.100.4-bionic1_amd64.deb)

(**First install**)So I install the .deb file use `sudo dpkg -i *.deb`,
and in my first install,
I set some wrong configurations(At that time,I didn't know we could change the configuration by changing default.json)
So I remove the `sgx-dcap-pccs` via `sudo dpkg -r *.deb` and delete the whole folders(/opt/intel/sgx-dcap-pcss).

(**Second install**)Then,I reinstall the deb file and cames a error:
`can't  open /opt/intel/sgx-dcap-pccs/config/default.json.There is no file or directory`

I'm surprised why first was succesed and second was fialed?

Does anyone know how to solve this problem?

Thanks a lot!

**Comment by lingyuj** [comment]
This issue happens because we changed the config file name. Could you please try below commands?
dpkg -i --force-confmiss xxxx.deb
or
uninstall the old package by "apt purge"
If the problem still can't be solved, please let us know. Sorry for your confusion.

**Comment by ltinerary** [comment]
> This issue happens because we changed the config file name. Could you please try below commands?
> dpkg -i --force-confmiss xxxx.deb
> or
> uninstall the old package by "apt purge"
> If the problem still can't be solved, please let us know. Sorry for your confusion.

Thank you！😊
I've just tried the advice you gave me and it's been very useful！

By the way，
I solved this problem by create a `default.json` file， 
And write the required key values to the file.

This may be a laborious method, but it will also solve the problem！
