### ISSUE TITLE
Logics behind CPUSVN

### ISSUE THREAD

**Issue by Ruide** [intel/SGXDataCenterAttestationPrimitives#185]
Hi,

I am using a multi-package platform. And my platform requires a bios update. Would you mind letting me know what the meaning of CPUSVN fields are?

My platform cpusvn is: 050502FFFFFF00000000000000000000 & pcesvn is: 0B00

The pck certificates' tcb retrieved from Intel PCS is:
"tcbm":"04040303FFFF000000000000000000000B00"

So what does the '02' in my CPUSVN '050502FFFFFF00000000000000000000' mean? Thank you!

**Comment by jsun39** [comment]
CPU SVN's definition is one internal data structure, Intel maybe will change it without notification to user. So I am afraid that I can't provide the CPUSVN fields meaning.  But from your platform's CPUSVN, it seems that your BIOS has some problem. I am not sure who is your BIOS vendor(I know some BIOS vendor's early version has some problem), please update your BIOS to the latest version.
