### ISSUE TITLE
QuoteVerificationSample Return sgx_qv_verify_quote failed: 0xe022

### ISSUE THREAD

**Issue by a3213105** [intel/SGXDataCenterAttestationPrimitives#189]
hi,  i meet an error when i test QuoteGeneration and QuoteVerification.  The steps I tested are as follows: 

- First i got quote.dat by QuoteGenerationSample, it seems to be successful :

root@icx04:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app
The project has been built in release hardware mode.
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent:
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:succeed!
Step2: Call create_app_report:succeed!
Step3: Call sgx_qe_get_quote_size:succeed!
Step4: Call sgx_qe_get_quote:succeed!cert_key_type = 0x5
sgx_qe_cleanup_by_policy is valid in in-proc mode only.

 Clean up the enclave load policy:succeed!
 

- second, i use QuoteVerificationSample to test the quote.dat, but it failed and return error below:

 
root@icx04:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteVerificationSample# ./app
Info: ECDSA quote path: ../QuoteGenerationSample/quote.dat

Trusted quote verification:
        Info: get target info successfully returned.
        Info: sgx_qv_set_enclave_load_policy successfully returned.
        Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: sgx_qv_verify_quote failed: 0xe022
        Error: Ecall: Verify QvE report and identity failed. 0xe013
        Error: App: Verification completed with Terminal result: a006

===========================================

Untrusted quote verification:
        Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: sgx_qv_verify_quote failed: 0xe022
        Error: App: Verification completed with Terminal result: a006

**Comment by jsun39** [comment]
What's your platform's type? production or pre-production platform?

**Comment by avalluri** [comment]
We are also facing the same issue while running the quote verification sample app on the pre-production platform.

**Comment by ardhipoetra** [comment]
Same issue on pre-production platform here. Details on #207.

**Comment by a3213105** [comment]
> What's your platform's type? production or pre-production platform?

it is a pre-production platform.  i have found support teams in SH, they have fix this error for me .

i will close this issue

**Comment by deliciousdish** [comment]
So，How to fix this error？
