### ISSUE TITLE
Error returned from the p_sgx_get_quote_config API. 0xe046

### ISSUE THREAD

**Issue by obaranov1** [intel/SGXDataCenterAttestationPrimitives#203]
Hello! I am facing the issue related to quote generation.  I deploy a container with sgx generation and verification in Azure AKS cluster using the Azure DCAP library. The sgx-quote-helper is installed in the cluster acting as the aesmd service. The PCCS server is served by Azure at https://global.acccache.azure.net/sgx/certificates/pckcrl?uri=https://certificates.trustedservices.intel.com/IntelSGXRootCA.crl&api-version=API_VERSION.  In this case, I do not specify values in /etc/sgx_default_qcnl.conf file as it is not needed.  However, for some reason, the platform cannot be recognized. Does anyone have a clue what is missing here to retrieve the quote data? 

`[get_platform_quote_cert_data ../qe_logic.cpp:347] Error returned from the p_sgx_get_quote_config API. 0xe046
2021-11-22T08:22:20.686Z        ERROR   setup   SGX initialization      {"error": "pkcs11: 0x5: CKR_GENERAL_ERROR"}
`

**Comment by lingyuj** [comment]
I think you need to use the Quote Provider library, aka QPL library, provided by Azure. Please check their document for how to replace quote provider library.
