### ISSUE TITLE
Establishing a secure channel of communication

### ISSUE THREAD

**Issue by JamesMenetrey** [intel/SGXDataCenterAttestationPrimitives#218]
Dear Intel developers,

Intel proposes an [thorough end-to-end attestation implementation using EPID](https://www.intel.com/content/www/us/en/developer/articles/code-sample/software-guard-extensions-remote-attestation-end-to-end-example.html) to establish a trusted channel of communication from the enclave to a relying party, using an adaptation of the SIGMA protocol.

From my understanding, this repository provides the tools and examples to generate quotes as files. Does Intel also provide additional insights/protocol about using DCAP to establish a secure channel of communication between an enclave and a relying party?

Many thanks!
Cheers

**Comment by jsun39** [comment]
I think you can refer to RA-TLS, It will be released in coming release.

**Comment by jdbeaney** [comment]
The SIGMA libraries for ECDSA based attestation are supported in the latest SDK and AESM.  That will tie a DCAP Quote with the SIGMA protocol and the quote can be verified with the DCAP QVL.  See the sample here:  https://github.com/intel/linux-sgx/tree/master/SampleCode/RemoteAttestation.  It will demonstrate the SIGMA protocol with both EPID and ECDSA.  But, you will need to link in the verifier as the quote verification is stubbed out in the samples.


But as mentioned above, there will be RA_TLS support specific for the DCAP release.

**Comment by JamesMenetrey** [comment]
Hello @jsun39 and @jdbeaney, many thanks for your insightful answers!
