### ISSUE TITLE
Error: verify quote failed with error code 0xe022 &0xe013

### ISSUE THREAD

**Issue by zhiminghufighting** [intel/SGXDataCenterAttestationPrimitives#221]
log as below:

[root@localhost tdx-quote-verification-sample]# sudo ./app quote quote.dat
Error: Unable to open quote file ../tdx-quote-generation-sample/quote.dat

Usage:
        Please specify quote path, e.g. "./app -quote <path/to/quote>"
        Default quote path is ../tdx-quote-generation-sample/quote.dat when no command line args

[root@localhost tdx-quote-verification-sample]# sudo ./app -quote quote.dat
Info: ECDSA quote path: quote.dat

Trusted quote verification:
        Info: get target info successfully returned.
        Info: sgx_qv_set_enclave_load_policy successfully returned.
        Info: tdx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: tdx_qv_verify_quote failed: 0xe022
        Error: Ecall: Verify QvE report and identity failed. 0xe013
        Error: App: Verification completed with Terminal result: a006

===========================================

Untrusted quote verification:
        Info: tdx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: tdx_qv_verify_quote failed: 0xe022
        Error: App: Verification completed with Terminal result: a006

platform:
EGS platform pre-production with tdx verify.
pccs status:

[root@localhost tdx-quote-verification-sample]# systemctl status pccs
● pccs.service - Provisioning Certificate Caching Service (PCCS)
   Loaded: loaded (/usr/lib/systemd/system/pccs.service; enabled; vendor preset: disabled)
   Active: active (running) since Wed 2022-03-16 09:49:33 EDT; 18min ago
     Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
 Main PID: 19527 (node)
    Tasks: 11 (limit: 1638622)
   Memory: 65.1M
   CGroup: /system.slice/pccs.service
           └─19527 /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js

Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.648 [info]: Client Request-ID : 197f60f5fdeb4c598f77b871ee3772b6
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.650 [info]: 127.0.0.1 - - [16/Mar/2022:14:07:00 +0000] "GET /sgx/certification/v4/r>
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.696 [info]: Client Request-ID : c8c012f4641447d0bc944a0fd4b4a2b1
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.698 [info]: 127.0.0.1 - - [16/Mar/2022:14:07:00 +0000] "GET /sgx/certification/v4/p>
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.704 [info]: Client Request-ID : 3f286aba599449fda17c320ce5f802c3
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.705 [info]: 127.0.0.1 - - [16/Mar/2022:14:07:00 +0000] "GET /tdx/certification/v4/t>
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.712 [info]: Client Request-ID : a4905592d0424408a4db31cf023e4f45
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.713 [info]: 127.0.0.1 - - [16/Mar/2022:14:07:00 +0000] "GET /tdx/certification/v4/q>
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.719 [info]: Client Request-ID : 68ddc40e34f546bd81e94422254026e9
Mar 16 10:07:00 localhost.localdomain node[19527]: 2022-03-16 10:07:00.722 [info]: 127.0.0.1 - - [16/Mar/2022:14:07:00 +0000] "GET /sgx/certification/v4/r>

[root@localhost PCKIDRetrievalTool_v1.10.91.2]# sudo ./PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.10.91.2

Registration status has been set to completed status.
the data has been sent to cache server successfully and pckid_retrieval.csv has been generated successfully!
[root@localhost PCKIDRetrievalTool_v1.10.91.2]#

I try to find the error code and can't find more clues.
BIOS config: SBX is select.

**Comment by andyzyb** [comment]
Please don't report TDX issue in this repo. It doesn't support TDX at this point.

**Comment by zhiminghufighting** [comment]
close it because find internal support, thanks!
