### ISSUE TITLE
Error: verify quote failed with error code 0xe016 &0xe013

### ISSUE THREAD

**Issue by zhiminghufighting** [intel/SGXDataCenterAttestationPrimitives#222]
log as below:
[root@localhost tdx-quote-verification-sample1]# sudo ./app -quote quote.dat
Info: ECDSA quote path: quote.dat

Trusted quote verification:
        Info: get target info successfully returned.
        Info: sgx_qv_set_enclave_load_policy successfully returned.
        Info: tdx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: tdx_qv_verify_quote failed: 0xe016
        Error: Ecall: Verify QvE report and identity failed. 0xe013
        Error: App: Verification completed with Terminal result: a006

===========================================

Untrusted quote verification:
        Info: tdx_qv_get_quote_supplemental_data_size successfully returned.
        Error: App: tdx_qv_verify_quote failed: 0xe022
        Error: App: Verification completed with Terminal result: a006

[root@localhost tdx-quote-verification-sample1]#

pccs & qgs status is ok as the same as #221 .

The HW is the same Archer City with same bios version based on MVPWW50.

platform:
EGS platform pre-production with tdx verify.

**Comment by andyzyb** [comment]
Please don't report TDX issue here.  This repo doesn't support TDX at this point.

**Comment by zhiminghufighting** [comment]
close it because find internal support, thanks!
