### ISSUE TITLE
Build error for QuoteVerificationSample: 'tdx_ql_qve_collateral_t’ does not name a type

### ISSUE THREAD

**Issue by marcelamelara** [intel/SGXDataCenterAttestationPrimitives#224]
I am in the process of testing my DCAP setup on Ubuntu 20.04 (kernel 5.13, FLC-enabled machine), and am able to run the QuoteGenerationSample successfully (DCAP_1.13 tag). However, when I run `make SGX_MODE=HW` for the QuoteVerificationSample, I encounter the following error:

```
In file included from App/App.cpp:42:
/usr/include/sgx_dcap_quoteverify.h:206:11: error: ‘tdx_ql_qve_collateral_t’ does not name a type; did you mean ‘sgx_ql_qve_collateral_t’?
  206 |     const tdx_ql_qve_collateral_t *p_quote_collateral,
      |           ^~~~~~~~~~~~~~~~~~~~~~~
      |           sgx_ql_qve_collateral_t
make[1]: *** [Makefile:224: App/App.o] Error 1
```

I have installed the latest libsgx PSW and DCAP libraries through apt (version 1.13.100), and have also ensured that the PCCS is running correctly.

Any insights would be greatly appreciated. Thank you!

**Comment by hyjiang** [comment]
Can you help to upgrade SDK to latest 2.16.100.4. The structure is introduced in latest release.

**Comment by marcelamelara** [comment]
Yes, I was still running SDK verison 2.15.1. Upgrading to version 2.16.100.4 fixed the issue. Thanks!
