### ISSUE TITLE
PCKRetrievalTool failed

### ISSUE THREAD

**Issue by deliciousdish** [intel/SGXDataCenterAttestationPrimitives#225]
when i execute PCKRetrievalTool，i got an error as follows:
```
Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.13.100.4

Warning: platform manifest is not available or current platform is not multi-package platform.
[CEnclavePool /home/caiqishen/linux-sgx/psw/urts/enclave.cpp:638] enter CEnclavePool constructor
[__sgx_create_enclave_ex urts.cpp:91] Couldn't open the enclave file, error = 2
Error, call sgx_create_enclave: fail [load_enclave], SGXError:200f.
```
I checked the code, it failed when load enclave "libsgx_id_enclave.signed.so.1"

It is ok in version 1.12.101.1 but failed in version  1.13.100.4. Is it a bug or  any suggestions?

**Comment by jsun39** [comment]
you build it by yourself, or use the prebuild version? It the prebuild version is used, stand-alone version or package version?

**Comment by deliciousdish** [comment]
I build it by myself, just "make" in "SGXDataCenterAttestationPrimitives/tools/PCKRetrievalTool"

**Comment by deliciousdish** [comment]
The latest Makefile is different from the version 1.12, and there is no pck_id_retrieval_tool_enclave.signed.so or libdcap_quoteprov.so.1 generated.

**Comment by jsun39** [comment]
you need build it for standalone version with command : make STANDALONE=1

Yes, the latest version has a significant change compared to previous version.

**Comment by deliciousdish** [comment]
i build it with command: make STANDALONE=1, but got the same error.

**Comment by jsun39** [comment]
maybe you need firstly execute: make clean

**Comment by deliciousdish** [comment]
I tried, but got the same error. I don't need this tool, so close this issue, thanks all.
