### ISSUE TITLE
The Confidentiality of the platform key

### ISSUE THREAD

**Issue by deliciousdish** [intel/SGXDataCenterAttestationPrimitives#227]
Accroding to the docs "Remote Attestation for Multi-Package Platforms using Intel® SGX Datacenter Attestation Primitives", the platform key was encrypted by RSEK and delivered to the registration authority service. And the RSEK was in the SGX Registration Server ID which was a self-signed structure. So It's easy to forger a register server ID which contains a RSEK produced by the attacker but not the registration authority service and the confidentiality of the platform key is broken. Is there other protection, for example, hardcoded a hash of the RSAK public key in a register to prevent the attack from forgering the register server ID?
![捕获](https://user-images.githubusercontent.com/2870121/164616797-3d1a47ff-cd04-4c77-bdbf-26f01aa6fd38.PNG)

**Comment by jsun39** [comment]
I am not sure whether I got your point.  In design/arch, user/thirdparty could provide their registration server, in this case they indeed need provide the RSAK and RSEK. 

Back to current scenario: Intel provide RSAK and RSEK, and Registration server.  If you means attack in BIOS level,  they indeed could replace RSAK and RSEK, but the registration should fail.

**Comment by deliciousdish** [comment]
An attacker can replace RSAK and RSEK, then get the platform manifest and decrypt the encrypted platform key. Then, set the register server id to intel Registration Server ID and the registration should success. In this process, the platform key will the same and not re-generated. But now the attacker have the plaintext of the platform key, then the pck can be derived and certify any attestation key. As a result, the quote can be tampered. Is that right?

**Comment by jdbeaney** [comment]
If the Registration Server ID is not signed by the Intel Registration service (RSAK) is different, then Intel the Registration Service will not produce the necessary certificates for a successful remote attestation.  So, an attacker can create its own Registration Server ID with its own RSAK and RSEK, but that platform will never be able to attest that it contains Intel CPUs with SGX capability in good standing using Intel as the root of trust.  
If you then change the Registration Server ID back to the Intel signed one, the platform provisioning keys will be regenerated and the previous values invalid.  I.e. The platform boot flow will revert to the Initial Platform Provisioning flow and new platform provisioning root keys will be generated.

**Comment by deliciousdish** [comment]
thanks, i checked the docs and it was mentioned in "3.3.1 Changing the Registration Authority Service".

**Comment by deliciousdish** [comment]
Thanks. I checked the docs and it was mentioned in "3.3.1 Changing the Registration Authority Service" and "B.1. SgxRegistrationConfiguration". But accroding to the docs, "On writes to this variable, the BIOS clears all platform registration data (KEY_BLOBS and PLATFORM_MANIFESTS). Any attempts to write to this variable when it is read-only are ignored", it was enforced by the BIOS, not microcode, but the BIOS is not in the TCB. If the BIOS is malicious and didn't clear the platform registration data, is that possible?

**Comment by jdbeaney** [comment]
No, the uCode loader module will detect the change in Registration Server ID and fail.  BIOS clearing the key blobs allows for a cleaner boot flow.  I.e.  Letting the uCode loader to fail will require a reboot to fix.  By clearing the data, the uCode loader will enter the IPE flow without failing.

**Comment by deliciousdish** [comment]
thanks, it'll all make sense.
