### ISSUE TITLE
Sample Quote warning with expiration_check_date

### ISSUE THREAD

**Issue by kruisdraad** [intel/SGXDataCenterAttestationPrimitives#230]
Hi,

The machines (several dell R450) has been installed on january 7 after that the system (After some troubleshooting) finally was able to generate AND verify a quote using the SampleCode. Now 5 months later, with the system untouched the same environment reports an error:

```
Info: ECDSA quote path: ../QuoteGenerationSample/quote.dat

Trusted quote verification:
        Info: get target info successfully returned.
        Info: sgx_qv_set_enclave_load_policy successfully returned.
        Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
        Info: App: sgx_qv_verify_quote successfully returned.
        Info: Ecall: Verify QvE report and identity successfully returned.
        Warning: App: Verification completed, but collateral is out of date based on 'expiration_check_date' you provided.
        Info: Supplemental data version: 3

===========================================

Untrusted quote verification:
        Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
        Info: App: sgx_qv_verify_quote successfully returned.
        Warning: App: Verification completed, but collateral is out of date based on 'expiration_check_date' you provided.
        Info: Supplemental data version: 3
```

Knowing SGX and new MCU / BIOS has been provided by the vendor, as well as SDK updated, we added the following changes (which under SGX1 usually solves issues):

- Pulled new from this repo
- Upgraded BIOS to latest version including MCU
- Upgrade SDK from 2.15.1 to 2.16.0
- Upgrade Ubuntu 20.04 (new kernel, from HWE, which pre-includes SGX)
- Upgrade Ubuntu packages (which installed a new PCCS)
- rebuild clean all the code.

However the error remains. The error is not very clear, some documentation states:

```
The expiration_check_date is used to compare to the x.509 ‘Not After’ field, x.509 CRL ‘Next Update’
and the JSON ‘nextUpdate’ field. If any of these collateral’s ‘Not After’ or ‘nextUpdate’ field has a date
earlier than the expiration_check_date input parameter, the value pointed by
Intel® Software Guard Extensions (Intel® SGX) Data Center Attestation Primitives:
ECDSA Quote Library API p_collateral_expiration_status will have a non-zero value. But this check alone will not cause the
Verify Quote API to return an error
```

Ok ... so we are hinted that it has to do with some certificate *somewhere*, which could be anywhere. There is no (clear) explaination what " inputted collateral" is and how it works ... and more importantly how to solve this.

**Comment by jsun39** [comment]
you need refresh your PCCS data to resolve this problem.

**Comment by lingyuj** [comment]
Simple way is to delete /opt/intel/sgx-dcap-pccs/pckcache.db and restart pccs service: sudo systemctl restart pccs
Or use the pccs admin tool:
python pccsadmin.py refresh

**Comment by kruisdraad** [comment]
> You can use the pccs admin tool https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/tools/PccsAdminTool python pccsadmin.py refresh

I am sorry, but this didnt help, it actually made it worse. The sample went from expired to unable to get quote:

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe047
Error in sgx_qe_get_target_info. 0xe047

The PCCS reports the platform was not in cache (duh!) but it did not attempt to renew it after the restart.

Also the pccsadmin.py is very buggy, when i tell it NOT to cache the password, it still wants to cache it and spits an error the keyring is missing. AFter installing keyring and just saving it i get an unauthorized, while i am pretty sure its the right password for admin.

Using PCKIDRetrievalTool solved updating the cache
