### ISSUE TITLE
The data struct of the platform_manifest

### ISSUE THREAD

**Issue by deliciousdish** [intel/SGXDataCenterAttestationPrimitives#231]
According to the document, the platform_manifest contains information about all CPU packages in the platform, signatures from all CPU packages using the PRK private keys, and the platform keys encrypted with the Registration Server’s Encryption Key (RSEK).
So, is there any docs about the detail data struct of the platform_manifest?
Thanks!

**Comment by TY-cc** [comment]
hi, Do you know the flow of DCAP? i have some questions ablout DCAP

**Comment by jsun39** [comment]
@deliciousdish ， for your question, platform_manifest was an internal structure. So for public/official doc, there will NO detail data struct of it.

**Comment by deliciousdish** [comment]
OK，thanks for your reply！ @jsun39
