### ISSUE TITLE
Is ED"GB"RD a typo of ED"BG"RD?

### ISSUE THREAD

**Issue by LeoneChen** [intel/SGXDataCenterAttestationPrimitives#236]
ED"GB"RD & ED"GB"WR is defined in [driver code](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/driver/linux/encls.h#L20)

They should be ED"BG"RD & ED"BG"WR
![image](https://user-images.githubusercontent.com/35480440/172788516-8df5f08e-2e71-458e-a4d7-c7724c2594e2.png)

It also in [linux upstream driver](https://github.com/torvalds/linux/blob/master/arch/x86/include/asm/sgx.h#L35)

**Comment by andyzyb** [comment]
Looks a typo, but not impact the function.
