### ISSUE TITLE
Test about SGX DCAP

### ISSUE THREAD

**Issue by TY-cc** [intel/SGXDataCenterAttestationPrimitives#246]
I want to test the DCAP function. Can i use the guide for [https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html](url) and [https://www.intel.com/content/www/us/en/developer/articles/technical/quote-verification-attestation-with-intel-sgx-dcap.html](url)?

**Comment by TY-cc** [comment]
When i install pccs, it keep repeating "fetchMetadata: sill pacote range manifest for aggre". i don't know what should i do?

**Comment by lingyuj** [comment]
> When i install pccs, it keep repeating "fetchMetadata: sill pacote range manifest for aggre". i don't know what should i do?

Is your machine behind a proxy server? If so you need to configure proxy for npm.

**Comment by TY-cc** [comment]
thanks. It is my network problem that can’t connect net.

Another problem is whether the DCAP must have the sgx enable？

**Comment by lingyuj** [comment]
> thanks. It is my network problem that can’t connect net.
> 
> Another problem is whether the DCAP must have the sgx enable？

Yes you need an sgx-enabled machine.

**Comment by TY-cc** [comment]
thanks， i have got a SGX machine. but it report 0xe019 when i runing Sample 


| |
cuichang1015
|
|
***@***.***
|
签名由网易邮箱大师定制
On 8/23/2022 ***@***.***> wrote：

thanks. It is my network problem that can’t connect net.

Another problem is whether the DCAP must have the sgx enable？

Yes you need an sgx-enabled machine.
