### ISSUE TITLE
Wrong member byte offsets in comments

### ISSUE THREAD

**Issue by thomasknauth** [intel/SGXDataCenterAttestationPrimitives#25]
I believe the comments are supposed to reference the offset in bytes within the structure. The offsets are wrong though.

https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/5685c0072b4596863a0f0401f9f570b083e7a745/QuoteGeneration/psw/quote_wrapper/common/inc/sgx_quote_3.h#L159

**Comment by llly** [comment]
The offsets in comments have been fixed.
