### ISSUE TITLE
about 0xe019 when runing the Samplecode-QuoteGeneration app

### ISSUE THREAD

**Issue by TY-cc** [intel/SGXDataCenterAttestationPrimitives#250]
This is error:
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe019
Error in sgx_qe_get_target_info. 0xe019

This si the status of pccs：
Loaded: loaded (/lib/systemd/system/pccs.service; enabled; vendor preset: enabled)
     Active: active (running) since Tue 2022-08-23 10:06:28 CST; 1h 17min ago
       Docs: https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/pccs/README.md
   Main PID: 16384 (node)
      Tasks: 11 (limit: 304001)
     Memory: 64.8M
     CGroup: /system.slice/pccs.service
             └─16384 /usr/bin/node -r esm /opt/intel/sgx-dcap-pccs/pccs_server.js

8月 23 10:06:28 user-NF5280M6 systemd[1]: Started Provisioning Certificate Caching Service (PCCS).
8月 23 10:06:28 user-NF5280M6 node[16384]: Tue, 23 Aug 2022 02:06:28 GMT morgan deprecated default format: use combined format at node_modules/esm/esm.js:1:2788>
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.209 [info]: DB Migration (Ver.0 -> 1) -- Start
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.214 [info]: DB Migration -- Done.
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.229 [info]: DB Migration (Ver.1 -> 2) -- Start
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.237 [info]: DB Migration -- Done.
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.249 [info]: DB Migration (Ver.2 -> 3) -- Start
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.257 [info]: DB Migration -- Done.
8月 23 10:06:30 user-NF5280M6 node[16384]: 2022-08-23 10:06:30.285 [info]: HTTPS Server is running on: https://localhost:8081

Do you have some suggestation？

**Comment by lingyuj** [comment]
Did you set proxy in your PCCS config file? By default the location is /opt/intel/sgx-dcap-pccs/config/default.json. You may need sudo privilege to modify it.

**Comment by TY-cc** [comment]
this is my /opt/intel/sgx-dcap-pccs/config/default.json
{
    "HTTPS_PORT" : 8081,
    "hosts" : "0.0.0.0",
    "uri": "https://api.trustedservices.intel.com/sgx/certification/v3/",
    "ApiKey" : "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "proxy" : " ",
    "RefreshSchedule": "0 0 1 * * *",
    "UserTokenHash" : "34d4e4af145ccd2cfffc8d46ba76314d44b0eba921302246f0b8b4177749923afd648b68f5c08389a778511d270ccfaaefa4d03fb64c2a39aa4c3552ee60e0d7",
    "AdminTokenHash" : "34d4e4af145ccd2cfffc8d46ba76314d44b0eba921302246f0b8b4177749923afd648b68f5c08389a778511d270ccfaaefa4d03fb64c2a39aa4c3552ee60e0d7",
    "CachingFillMode" : "REQ",
    "LogLevel" : "info",
    "DB_CONFIG" : "sqlite",
    "sqlite" : {
        "database" : "database",
        "username" : "username",
        "password" : "password",
        "options" : {
            "host": "localhost",
            "dialect": "sqlite",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false, 
            "storage": "pckcache.db"
        }
    }, 
    "mysql" : {
        "database" : "pckcache",
        "username" : "root",
        "password" : "mypass",
        "options" : {
            "host": "localhost",
            "dialect": "mysql",
            "pool": {
                "max": 5,
                "min": 0,
                "acquire": 30000,
                "idle": 10000
            },
            "define": {
                "freezeTableName": true
            },
            "logging" : false
        }
    }
}

**Comment by TY-cc** [comment]
I will raise a new issue about install the SGX-DCAP-Samplecode with more detail.
