### ISSUE TITLE
How can i get certificate for the pccs? 

### ISSUE THREAD

**Issue by TY-cc** [intel/SGXDataCenterAttestationPrimitives#260]
I want test samplecode for non-self-signed mode.  But my pccs's log as follow:

![image](https://user-images.githubusercontent.com/86347316/190985606-a123f9bf-8b08-4307-8d2b-add0f51245cc.png)

How  to get and setup the key and certrification?

**Comment by lingyuj** [comment]
You need to put the private key and signed certificate in the /ssl_key folder.

**Comment by lingyuj** [comment]
Just FYI: https://www.beyondtrust.com/docs/remote-support/how-to/sslcertificates/create-ca-signed.htm

**Comment by TY-cc** [comment]
Thanks，I will see how to apply for a certificate at [https://www.beyondtrust.com/docs/remote-support/how-to/sslcertificates/create-ca-signed.htm](url). i close this issue
