### ISSUE TITLE
There are some problems about PCK(Provision Cerificate Key)

### ISSUE THREAD

**Issue by TY-cc** [intel/SGXDataCenterAttestationPrimitives#267]
How and When create the  PCK？ What is it related to？

**Comment by TY-cc** [comment]
In remote authentication, PCK in PCE is used to sign the authentication key (AK) of QE. I am more curious about when PCK was generated ? How is it generated ?

About enclave. In my understanding, when we create an enclave, the enclave is automatically signed by us. Is my understanding correct ? If correct, how do we control the signing key when creating an enclave ? Or how to get the signature key ? If not, what is correct ?

**Comment by dashuaic** [comment]
PCK is derived from SGX provisioning root key(known by Intel) with some knowledge of your software(unknow by (known by Intel).
Any key can be signing key. But only PCE only signed by Intel can get the expected PCK same with Intel server.

**Comment by TY-cc** [comment]
About this sentence，my understanding is that intel will also generate PCK. Right ? 
>  only PCE only signed by Intel can get the expected PCK same with Intel server

I also have some questions about the product environment and test environment of DCAP.
In the test environment, we set up self-signed certificates for pccs. How does the intel service determine that a pccs is valid ? Rely on our subscription DCAP key ? 

In the product environment, what do we need to pay to get the support of intel certificate service ?

**Comment by dashuaic** [comment]
If user register their platform (send the knowledge of your software), then Intel can generate same PCK with client, if missing that information, Intel can NOT generate the expected PCK.
PCCS is just a cache server passing message between client and server. Server will check subscription key to handle request.
You can refer https://api.portal.trustedservices.intel.com/documentation

**Comment by TY-cc** [comment]
_PCCS is just a cache server passing message between client and server. Server will check subscription key to handle request_
I can 't understand exactly what you mean. Is the client sgx platform ? Is the server intel ?

Then regardless of the product or test environment, if we need intel services, we only need to subscribe to a key.

**Comment by dashuaic** [comment]
Yes, the client is SGX platform, and the server is Intel. SGX platform can get the cert without PCCS.  
PCCS is for the environment where the SGX client can't access Intel server (PCCS can access Intel server).
From server perspective, each request for a cert needs a key. 
For PCCS, it may request multiple certs (for different SGX platforms) with PCCS's key, then it can deliver cert to SGX platform.
If SGX platform get cert from PCCS, whether need a key depends on PCCS.  In practice, PCCS doesn't do authenticate every request from SGX platform, since they are in the same LAN.

**Comment by TY-cc** [comment]
Thank you very much. You confirmed my idea.
The other question is what is the difference between DCAP test environment and product environment ? There is only one difference in my understanding. The test environment uses unsafe self-visa certificates, and the product environment uses formal certificates. Are there other differences ?

**Comment by dashuaic** [comment]
I am not sure what is "DCAP test environment", what is different with product environment?

**Comment by TY-cc** [comment]
DCAP Test Environment Configuration：
1：When installing pccs, I use an unsafe self-signed certificate.
2：In /etc/sgx_default_qcnl.conf, I set "use _secure_cert" to false.

If I want to use it officially, do I just need to replace a secure certificate ? And  set “use_secure_cert” to true.

**Comment by lingyuj** [comment]
> DCAP Test Environment Configuration： 1：When installing pccs, I use an unsafe self-signed certificate. 2：In /etc/sgx_default_qcnl.conf, I set "use _secure_cert" to false.
> 
> If I want to use it officially, do I just need to replace a secure certificate ? And set “use_secure_cert” to true.

Yes, use a formally signed certificate and set use_secure_cert to true should work.

**Comment by TY-cc** [comment]
Thank you very much. I close this issue.
Thanks again!!
