### ISSUE TITLE
How to derive Attestation Key Cert signed by PCK?

### ISSUE THREAD

**Issue by DCMMC** [intel/SGXDataCenterAttestationPrimitives#268]
I got the PCK certificate from `https://api.trustedservices.intel.com/sgx/certification/v4/pckcert` and `PCKRetrievalTool`. If I had a Key Pair, how can I sign it and create a leaf certificate using PCK as shown in the below figure? I have no idea where the corresponded private key for this PCK certifcate is stored. Therefore, I cannot sign and issue downstream certificates using this PCK certificate.

According to the [document](https://download.01.org/intel-sgx/sgx-dcap/1.7/linux/docs/Intel_SGX_ECDSA_QuoteLibReference_DCAP_API.pdf)(in Section 2.1) provided by Intel, the PCK private key is rooted to the CPU HW fuses and genrated only by PCE (Provisioning Certification Enclave). So my question is how to get PCK private key or could you please give me an example to issue certificates using the PCK certificate? Thanks in advance.

<img width="428" alt="image" src="https://user-images.githubusercontent.com/8016514/198719624-05a3572c-143f-40d9-b8ce-e714a39a6aac.png">

**Comment by dashuaic** [comment]
For Intel® SGX DCAP, the QE will generate the ECDSA Attestation Key (AK) and include a hash of the AK in the QE.REPORT.ReportData. Only the PCE can produce the PCK private key and sign QE.REPORT. The PCE certification data will ultimately be embedded in the ECDSA Quote generated by the QE.  This this the whole trusted chain.
If you want use your Key Pair, you need implement yourself QE that replace Intel QE.
