### ISSUE TITLE
No cache data for this platform

### ISSUE THREAD

**Issue by lili8808** [intel/SGXDataCenterAttestationPrimitives#278]
I am beginner to SGX DCAP, I am using vm with kernel 5.15 . I configured pccs on my vm using link https://www.intel.com/content/www/us/en/developer/articles/guide/intel-software-guard-extensions-data-center-attestation-primitives-quick-install-guide.html
I run `sudo systemctl start pccs` and `curl -k -G "https://localhost:8081/sgx/certification/v4/rootcacrl"` but I get error `No cache data for this platform.`
I have no idea where is the problem.

**Comment by llly** [comment]
What command or log says `No cache data for this platform.`?  the `curl` command doesn't return it.

**Comment by lili8808** [comment]
I saw the error inside  pccs_server.log but now the problem with the curl command solved.
