### ISSUE TITLE
cannot open output file src/main/c/lib/libjni_dcap_quoteverify.so.1: No such file or directory

### ISSUE THREAD

**Issue by zinginging** [intel/SGXDataCenterAttestationPrimitives#289]
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4a1656b1c5baf2366898a9dc44d77483aac6fe1e/SampleCode/JavaQuoteVerificationSample/README.md?plain=1#L37
Return ERROR when I execute this command, `make` returns the same error as blow:
cc -shared -Wl,-soname=libjni_dcap_quoteverify.so -o src/main/c/lib/libjni_dcap_quoteverify.so.1 src/main/c/jni/sgx_dcap_quoteverify_wrap.o src/main/c/jni/jni_native_lib_init.o
/usr/local/bin/ld: cannot open output file src/main/c/lib/libjni_dcap_quoteverify.so.1: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [Makefile:72: lib_jni_dcap_quoteverify] Error 1

I create **lib** dir in src/main/c and solved this problem. 
I think this dir should be added to the source code.

**Comment by dashuaic** [comment]
Yes, the lib directory will be created firstly if not exist in there. The upcoming release 1.16 will have this fix.
Thanks

**Comment by llly** [comment]
Fixed in DCAP 1.16 release.
