### ISSUE TITLE
qeReport is null

### ISSUE THREAD

**Issue by zinginging** [intel/SGXDataCenterAttestationPrimitives#292]
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/cc582e8be0c9010295c66fb58c59f74744017600/SampleCode/JavaQuoteVerificationSample/src/main/java/com/intel/sgx/Demo.java#L70

I use this java demo to verify a quote file and get sgxDcapQuoteVerifyResult like below.
mrenclave is in qeReport but the result is null，is there anything wrong? How can I get the mrenclave in this java demo？
And `"verifyResult": 0`, Does 0 mean passed the attestation or not?
```json
"sgxDcapQuoteVerifyResult": {
            "verifyResult": 0,
            "qlQvResult": "SGX_QL_QV_RESULT_CONFIG_AND_SW_HARDENING_NEEDED",
            "qeReport": null
}

```

**Comment by zinginging** [comment]
And `"verifyResult": 0`, Does 0 mean passed the attestation or not?

**Comment by llly** [comment]
In current implementation, `qeReport` is always NULL.
It is designed to contain QVE report info.  See comment https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/71557c7d1d869b6bd6f95566c051cbd098549509/SampleCode/JavaQuoteVerificationSample/src/main/c/jni/sgx_dcap_quoteverify_wrap.c#L897

You can parse quote[112 - 144] to retrieve mrenclave of user enclave.

`verifyResult` is error code of `quote3_error_t`. 0 means that successful and `qlQvResult` is valid.
`qlQvResult` is result of quote verification, which is error code of `sgx_ql_qv_result_t`.
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/71557c7d1d869b6bd6f95566c051cbd098549509/QuoteVerification/QvE/Include/sgx_qve_header.h#L60-L63

**Comment by dashuaic** [comment]
Currently, the wrapper only for QVL and only support untrusted verification, so the qeReport is NULL.
"verifyResult": 0, means the quote is passed verification. the "SGX_QL_QV_RESULT_CONFIG_AND_SW_HARDENING_NEEDED", means the TCB need to update.

**Comment by FunnyShelby** [comment]
> 目前，包装器仅适用于 QVL，并且仅支持不受信任的验证，因此 qeReport 为 NULL。 “verifyResult”： 0，表示报价通过验证。“SGX_QL_QV_RESULT_CONFIG_AND_SW_HARDENING_NEEDED”表示 TCB 需要更新。

However, the tcb shown in this information is already the latest, does it need to be updated?

**Comment by FunnyShelby** [comment]
> 在当前实现中，始终为 NULL。它旨在包含 QVE 报告信息。查看评论`qeReport`
> 
> https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/71557c7d1d869b6bd6f95566c051cbd098549509/SampleCode/JavaQuoteVerificationSample/src/main/c/jni/sgx_dcap_quoteverify_wrap.c#L897
> 
> 您可以解析 quote[112 - 144] 以检索用户 enclave 的 mrenclave。
> 
> `verifyResult`是 的错误代码。0 表示成功且有效。是报价验证的结果，是 的错误代码。`quote3_error_t``qlQvResult``qlQvResult``sgx_ql_qv_result_t`
> 
> https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/71557c7d1d869b6bd6f95566c051cbd098549509/QuoteVerification/QvE/Include/sgx_qve_header.h#L60-L63

Do you mean you need to install some more patches？

**Comment by dashuaic** [comment]
Do you have hyperthreading enabled in your BIOS? If so, can you disable it to check? If you run sample in https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/main/SampleCode/QuoteVerificationSample, you should see the security advisory for your attesting platform.
