### ISSUE TITLE
[error]: Intel PCS server returns error. Error code : 404  Error: No cache data for this platform.

### ISSUE THREAD

**Issue by jiangxu12** [intel/SGXDataCenterAttestationPrimitives#298]
My server used to be a centOS system, I recently changed it to ubuntu20.04.
On the CentOS system, I have configured DCAP correctly and run the Sample successfully.
But after I reinstalled my OS to Ubuntu, I reinstalled the sgx driver and pccs and reconfigured the DCAP environment, the following error was reported when the command **PCKIDRetrievalTool** was executed.
I have reset my SGX from BIOS.

```
root@lenovo:/opt/intel# PCKIDRetrievalTool

Intel(R) Software Guard Extensions PCK Cert ID Retrieval Tool Version 1.16.100.2

Warning: platform manifest is not available or current platform is not multi-package platform.
Error: unexpected error occurred while sending data to cache server.
pckid_retrieval.csv has been generated successfully, however the data couldn't be sent to cache server!
```
I check the logs in **sgx-dcap-pccs/logs/pccs_server.log** 

```
2023-03-18 13:48:12.142 [info]: HTTPS Server is running on: https://localhost:8081
2023-03-18 13:54:16.672 [info]: HTTPS Server is running on: https://localhost:8081
2023-03-18 13:54:27.832 [info]: Client Request-ID : 52b0103afda648c28e45b4dc313bb57b
2023-03-18 13:54:29.398 [info]: Request-ID is : c2a1264c935e411e855df66487fba9e4
2023-03-18 13:54:29.402 [error]: Intel PCS server returns error(404).
2023-03-18 13:54:29.402 [error]: Intel PCS server returns error. Error code : 404
2023-03-18 13:54:29.403 [error]: Error: No cache data for this platform.
    at Module.getPckCertFromPCS (file:///opt/intel/sgx-dcap-pccs/services/logic/commonCacheLogic.js:92:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async LazyCachingMode.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/caching_modes/cachingMode.js:163:7)
    at async Module.registerPlatforms (file:///opt/intel/sgx-dcap-pccs/services/platformsRegService.js:107:3)
    at async postPlatforms (file:///opt/intel/sgx-dcap-pccs/controllers/platformsController.js:40:5)
2023-03-18 13:54:29.410 [info]: 127.0.0.1 - - [18/Mar/2023:13:54:29 +0000] "POST /sgx/certification/v3/platforms HTTP/1.1" 404 32 "-" "-"
```
Why does this happen, is it related to the fact that I have provisioning the platform before on the previous OS.
In addition, I am using the newly acquired **api key**

**Comment by jsun39** [comment]
It seems that it was not related "new api key".  When you say "I have reset my SGX from BIOS", does it means: you have done "SGX Factory reset"? If yes, I am a litter confusion, if you have done "SGX Factory reset", then this tool should not pop-up some warning message "Warning: platform manifest is not available or current platform is not multi-package platform.". If No, please do "SGX Factory reset"

**Comment by jiangxu12** [comment]
> It seems that it was not related "new api key". When you say "I have reset my SGX from BIOS", does it means: you have done "SGX Factory reset"? If yes, I am a litter confusion, if you have done "SGX Factory reset", then this tool should not pop-up some warning message "Warning: platform manifest is not available or current platform is not multi-package platform.". If No, please do "SGX Factory reset"

Thanks,I do "SGX Factory reset" again,it works.
But there is another error, when I try the Sample QuoteGenerationSample.
 It could make succeeefully, but when I run the app.
There is an error like this :

```
root@lenovo:/opt/intel/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app
sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
set the enclave load policy as persistent:succeed!

Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe065
Error in sgx_qe_get_target_info. 0xe065
```

What does this mean?

**Comment by jiangxu12** [comment]
> > It seems that it was not related "new api key". When you say "I have reset my SGX from BIOS", does it means: you have done "SGX Factory reset"? If yes, I am a litter confusion, if you have done "SGX Factory reset", then this tool should not pop-up some warning message "Warning: platform manifest is not available or current platform is not multi-package platform.". If No, please do "SGX Factory reset"
> 
> Thanks,I do "SGX Factory reset" again,it works. But there is another error, when I try the Sample QuoteGenerationSample. It could make succeeefully.But when I run the app,there is an error like this :
> 
> ```
> root@lenovo:/opt/intel/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample# ./app
> sgx_qe_set_enclave_load_policy is valid in in-proc mode only and it is optional: the default enclave load policy is persistent: 
> set the enclave load policy as persistent:succeed!
> 
> Step1: Call sgx_qe_get_target_info:[get_platform_quote_cert_data ../qe_logic.cpp:378] Error returned from the p_sgx_get_quote_config API. 0xe065
> Error in sgx_qe_get_target_info. 0xe065
> ```
> 
> What does this mean?

I have solve this problem.
I nees to set use_secure_cert to false in /etc/sgx_default_qcnl.conf.
