### ISSUE TITLE
Private keys in repository

### ISSUE THREAD

**Issue by jethrogb** [intel/SGXDataCenterAttestationPrimitives#3]
Are these files supposed to be public?

https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/psw/quote_wrapper/quote/enclave/qe3_private.pem
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/psw/quote_wrapper/quote/MSFTtestkey.h

**Comment by andyzyb** [comment]
Thanks for reporting this.  The key was used for test purpose and it is no longer needed. We'll remove it.  
Although It is not some secret since the key was generated as a temporary one.

**Comment by llly** [comment]
These files have been removed.
