### ISSUE TITLE
sgx-dcap-quoteverify::tee_qv_get_collateral() totally unsound and broken by design

### ISSUE THREAD

**Issue by haraldh** [intel/SGXDataCenterAttestationPrimitives#310]
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4cb5c8b81f126f9aa3ee921d7980a909a9bd676d/QuoteVerification/dcap_quoteverify/sgx-dcap-quoteverify-rs/src/lib.rs#L333-L405

In my first naive usage, I stored the bytes in a const for some test cases, which of course leads to: `SIGSEGV, Segmentation fault`, if the collateral is used in `intel_tee_quote_verification_rs::tee_verify_quote`.

The return `Vec<u8>` cannot be used after using `Copy` or `Clone`, because this is essentially a self referencing struct.
It's also unsound, because Rust is allowed to move the Vec in memory as it likes. Maybe `Pin` can help, but all in all this is not very Rust ideomatic. Better use a new struct with some `Vec` members and serialize to and from this new struct to the C original.

**Comment by yao-ji** [comment]
Fixed in #320
