### ISSUE TITLE
TDX Quote verification failing with 0xe032

### ISSUE THREAD

**Issue by vkarpenk** [intel/SGXDataCenterAttestationPrimitives#316]
TDX Quote verification failing with the following error:

..QuoteVerificationSample> ./app -quote quote.dat
Info: ECDSA quote path: quote.dat

Untrusted quote verification:
        Info: tee_get_quote_supplemental_data_version_and_size successfully returned.
        Info: latest supplemental data major version: 3, minor version: 1, size: 336
        Error: App: tee_verify_quote failed: 0xe032
        Error: App: Verification completed with Terminal result: a006

PCCS v4 endpoint is used for quote generation/verification. MPA registration and tdx quote generation is successful.

PCCS log: 

2023-05-26 13:14:30.728 [info]: Client Request-ID : 5058b9ec1cf64fe6bd3b5d892eae0b92
2023-05-26 13:14:30.732 [info]: 127.0.0.1 - - [26/May/2023:13:14:30 +0000] "GET /sgx/certification/v4/pckcrl?ca=platform HTTP/1.1" 200 5326 "-" "-"

2023-05-26 13:14:30.751 [info]: Client Request-ID : 50bc61366f984d64b258a478ab6ee3ff
2023-05-26 13:14:30.757 [info]: 127.0.0.1 - - [26/May/2023:13:14:30 +0000] "GET /tdx/certification/v4/tcb?fmspc=00806F050000 HTTP/1.1" 200 2400 "-" "-"

2023-05-26 13:14:30.783 [info]: Client Request-ID : a60a84b7609945cab708a396c2ead7b1
2023-05-26 13:14:30.787 [info]: 127.0.0.1 - - [26/May/2023:13:14:30 +0000] "GET /tdx/certification/v4/qe/identity HTTP/1.1" 200 624 "-" "-"

2023-05-26 13:14:30.814 [info]: Client Request-ID : 9381bc7d213a452183da8706f072326b
2023-05-26 13:14:30.820 [info]: 127.0.0.1 - - [26/May/2023:13:14:30 +0000] "GET /sgx/certification/v4/rootcacrl HTTP/1.1" 200 586 "-" "-"

What causes the 0xe032 SGX_QL_TCB_REVOKED error? Please share any advice on how to debug/fix it.

**Comment by jsun39** [comment]
which version DCAP software was used? And would you please attach your quote?

**Comment by dashuaic** [comment]
The QVE and TCB seem to be ok. But the QE's isvsvn is 3 which is lower, can you upgrade your QE to check?

**Comment by vkarpenk** [comment]
Thanks, what are the steps to upgrade QE? 

Inside the TDX VM we have the following packages and versions installed for quote generation: 
libsgx-ae-qe3.x86_64                                              1.16.100.2-1.el8
libsgx-qe3-logic.x86_64                                           1.16.100.2-1.el8
libsgx-ae-tdqe.x86_64                                             1.16.100.2-1.el8
libsgx-qe3-logic-debuginfo.x86_64                                 1.16.100.2-1.el8

On the host, we have the following packages installed for quote verification:
libsgx-ae-qve                              1.16.100.2-focal1
libsgx-dcap-quote-verify                   1.16.100.2-focal1 
libsgx-dcap-quote-verify-dev               1.16.100.2-focal1

**Comment by vkarpenk** [comment]
The quote verification still fails with  0xe032 after installing this package:
libsgx-ae-tdqe                             1.16.100.2-focal1

**Comment by dashuaic** [comment]
The svn of 1.16 should be 4, but from the quote.dat,  I saw the svn is 3.
You can use below command to dump the metadata of tdqe.
`sgx_sign dump -enclave /lib64/libsgx_tdqe.signed.so.1 -dumpfile tdqe.meta.txt`
You may need `source /opt/intel/sgxsdk/environment` firstly, if sgx_sign is not in PATH. Please attach the meta file.

**Comment by vkarpenk** [comment]
I found this in /usr/lib/x86_64-linux-gnu. The meta file is attached. 

lrwxrwxrwx  1 root root       32 Mar  2 08:49 libsgx_tdqe.signed.so.1 -> libsgx_tdqe.signed.so.1.16.100.1
-rw-r--r--  1 root root  1216880 Mar  2 08:49 libsgx_tdqe.signed.so.1.16.100.1

[tdqe.meta.txt](https://github.com/intel/SGXDataCenterAttestationPrimitives/files/11592408/tdqe.meta.txt)

**Comment by jsun39** [comment]
this tdqe's svn is 4. It seems that your quote is not generated by this TDQE. Would you please check:
1. whether there are any other version libsgx_tdqe.signed.so.1 in your environment except /usr/lib/x64_64-linux-gun?
2. whether the quote was one stale ?
