### ISSUE TITLE
QE Attestation key is the same?

### ISSUE THREAD

**Issue by water5-cmd** [intel/SGXDataCenterAttestationPrimitives#326]
Hi, develops!
On the same platform and the same enclave, will QE generate a different Attestation Key each time when remote authentication is performed?
From the paper 'Supporting Third Party Attestation for Intel® SGX with Intel® Data Center Attestation Primitives', I found the following passage:
> The Intel Quoting Enclave generates the attestation key using a derivative of its Seal Key (from EGETKEY) as a seed to a key derivation algorithm in order to generate a repeatable signing key. This key is not known to Intel and changes to OwnerEpoch will cause a new Attestation Key to be developed, but **this key will be the same when generated anywhere on the platform at the same TCB and across resets and does not require persistent storage.** 
> If it’s desired that the same Quoting Enclave generate a different key, for example when invoked in different VMs, a QE developer can alternatively generate the attestation key using the hardware DRNG. Note that this will give different VMs unique 
Quoting Keys, but they will be certified by the same platform Provisioning Certification Enclave (PCE).
> If a new attestation key is required, such as after a TCB Recovery, the Quoting Enclave generates a new ECDSA key using the same procedure.

Does this mean that QE will not generate a new AK after generating the AK, unless the TCB is updated or needs to generate a new AK?
Thanks for your help!

**Comment by llly** [comment]
Correct. https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/4cb5c8b81f126f9aa3ee921d7980a909a9bd676d/QuoteGeneration/quote_wrapper/quote/enclave/quoting_enclave_3.cpp#L1011
`key_id` is used to generate different key in EGETKEY. We don't allow modification of key_id in AE key generation of QE.

**Comment by water5-cmd** [comment]
Thanks!
AK is the same, that is to say, when multiple enclaves on one SGX machine perform remote attestation, QE uses AK to sign the report. Am I understanding this right?

**Comment by llly** [comment]
Right.
