### ISSUE TITLE
Should User Enclave validate QE MREnclave from Quote before calling QvE?

### ISSUE THREAD

**Issue by hu6360567** [intel/SGXDataCenterAttestationPrimitives#331]
![image](https://github.com/intel/SGXDataCenterAttestationPrimitives/assets/1241597/6ce81c8b-875e-4ed5-9b82-324298715382)
As the workflow shows, qe_identity is passed from untrusted code; also,qe identity of remote platform is not included in the supplemental data. Then if the user enclave does not validate the qe identity from the quote, then the qe identity is controlled by the untrusted code somehow.
Is that OK?

**Comment by hyjiang** [comment]
QE identity is same with other collaterals, all the collaterals are signed by Intel, which means it is protected by Intel root of trusted eventually.
If any of the collateral are changed/hacked by untrusted code, quote verification will fail.

**Comment by hu6360567** [comment]
> QE identity is same with other collaterals, all the collaterals are signed by Intel, which means it is protected by Intel root of trusted eventually. If any of the collateral are changed/hacked by untrusted code, quote verification will fail.

Since third party is able to implement its own QE, how the intel ensure all the QEs' security? Can the user enclave be aware of the remote QE identity? I'd like to make a whitelist of QE, so that report generated by a whitelisted QE is acceptable.

**Comment by hu6360567** [comment]
Sorry, I mean should I check the QE MREnclave, not the QE Identity.

**Comment by hyjiang** [comment]
If you want to develop your own QE, then the whole story is different. 
Basically you need to publish your own OE identity, and you need to your own version quote verification library. Intel cannot guarantee the QE security in this case.

User enclave can check QE identity or extract QE report from quote to get corresponding information, including MREnclave.
