### ISSUE TITLE
QVS: make it possible to get early tcbs from pcs

### ISSUE THREAD

**Issue by nmwael** [intel/SGXDataCenterAttestationPrimitives#332]
please make it possible to get early tcb advisories so that pcs will use https://api.trustedservices.intel.com/sgx/certification/v4/tcb?update=early as described here:
https://api.portal.trustedservices.intel.com/documentation

Could be exposed via this env:
QVS_PCS_CLIENT_TCB_UPDATE

with possible values, standard or early where standard are default.

**Comment by nmwael** [comment]
how is this going along?

**Comment by bsulich2** [comment]
Hi,

we implemented QVS update parameter. More information below:

- [PR: Release ww04-2](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/pull/7/commits/d81f0027a5ac99c3374c95b1ec9ef950de8fc0dc)
- [PR: Release ww05](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/pull/8/files) 
- Please take a look at [swagger.json](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/blob/stable/swagger.json) that demonstrates how to use new query parameter.

At the end, please note, that **QVS** and **QVL** became submodules of this repository. Therefore if you use QVS or QVL independently consider switching to one of submodules directly. New issues/discussions related to QVS or QVL should be started in submodules.

- [Intel® Software Guard Extensions and Intel® Trust Domain Extensions Data Center Attestation Primitives (Intel® SGX and Intel® TDX DCAP) Quote Verification Service](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService)
- [Intel(R) Software Guard Extensions Data Center Attestation Primitives for Linux* / Windows* OS: Quote Verification Library](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationLibrary)

**Comment by bsulich2** [comment]
Hi,

we implemented QVS update parameter. More information below:

- [PR: Release ww04-2](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/pull/7/commits/d81f0027a5ac99c3374c95b1ec9ef950de8fc0dc)
- [PR: Release ww05](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/pull/8/files) 
- Please take a look at [swagger.json](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService/blob/stable/swagger.json) that demonstrates how to use new query parameter.

At the end, please note, that **QVS** and **QVL** became submodules of this repository. Therefore if you use QVS or QVL independently consider switching to one of submodules directly. New issues/discussions related to QVS or QVL should be started in submodules.

- [Intel® Software Guard Extensions and Intel® Trust Domain Extensions Data Center Attestation Primitives (Intel® SGX and Intel® TDX DCAP) Quote Verification Service](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationService)
- [Intel(R) Software Guard Extensions Data Center Attestation Primitives for Linux* / Windows* OS: Quote Verification Library](https://github.com/intel/SGX-TDX-DCAP-QuoteVerificationLibrary)
