### ISSUE TITLE
make sign error

### ISSUE THREAD

**Issue by chao-novovivo** [intel/SGXDataCenterAttestationPrimitives#34]
Hi,

When I followed the instruction of executing the command: make sign. 
As I google the problem, it says that I use the (1.1.0) OpenSSL version instead of the (1.0.x) one. Is that the reason why I met the problem. Could you please help me confirm the situation? and Any advice for solving this problem? Thanks for your time.
 
https://stackoverflow.com/questions/46768071/openssl-linking-undefined-reference-evp-md-ctx-new-and-fre

It has some error:
make[1]: Entering directory '/usr/src/linux-headers-4.11.2-041102-generic'
  HOSTCC  /home/novo1/chao-DataCenter/SGXDataCenterAttestationPrimitives-master/driver/linux/le/enclave/sgxsign
/tmp/ccVzfgkI.o: In function `measure_encl':
sgxsign.c:(.text+0x4a1): undefined reference to `EVP_MD_CTX_new'
sgxsign.c:(.text+0x518): undefined reference to `EVP_MD_CTX_free'
sgxsign.c:(.text+0x5af): undefined reference to `EVP_MD_CTX_free'
sgxsign.c:(.text+0x7f7): undefined reference to `EVP_MD_CTX_free'
/tmp/ccVzfgkI.o: In function `usesig':
sgxsign.c:(.text+0xa27): undefined reference to `RSA_get0_key'
sgxsign.c:(.text+0xa86): undefined reference to `RSA_get0_key'
sgxsign.c:(.text+0xb17): undefined reference to `RSA_get0_key'
/tmp/ccVzfgkI.o: In function `sign':
sgxsign.c:(.text+0xe3a): undefined reference to `RSA_get0_key'
sgxsign.c:(.text+0xe9b): undefined reference to `RSA_get0_key'
/tmp/ccVzfgkI.o:sgxsign.c:(.text+0xf20): more undefined references to `RSA_get0_key' follow
collect2: error: ld returned 1 exit status

**Comment by andyzyb** [comment]
Which Linux distro you are using?  We currently only support Ubuntu 16.04 and 18.04.

**Comment by chao-novovivo** [comment]
ubuntu 16.04 with kernel upgraded to 4.11.2-041102-generic

**Comment by andyzyb** [comment]
So can you try to upgrade to openssl 1.1.0+?

**Comment by chao-novovivo** [comment]
I type command: openssl version. 
it shows: OpenSSL 1.1.0g  2 Nov 2017

**Comment by chao-novovivo** [comment]
After reinstalling OpenSSL 1.0.2, fix the errors.
