### ISSUE TITLE
Wrong format of default sgx_default_qcnl.conf

### ISSUE THREAD

**Issue by qzheng527** [intel/SGXDataCenterAttestationPrimitives#343]
In the [sgx_default_qcnl.conf](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/master/QuoteGeneration/qcnl/linux/sgx_default_qcnl.conf#L8), why there are some "," in the first place of several lines? such as  **,"use_secure_cert": true**.

**Comment by dashuaic** [comment]
As I understand it, the comma is moved to the beginning of the line. This prevents the comma from missing after the value is changed.
