### ISSUE TITLE
PCCS docker container image build error

### ISSUE THREAD

**Issue by yangfh2004** [intel/SGXDataCenterAttestationPrimitives#355]
When using the dockerfile in `QuoteGeneration/pccs/container` to build an image for PCCS services, it will throw an error due to the missing SGX SDK dependency.

I reviewed the Makefile in the directory `/SGXDataCenterAttestationPrimitives/tools/PCKCertSelection/PCKCertSelectionLib`, and found that it needs to load the `QuoteGeneration/buildenv.mk`, which loads `/opt/intel/sgxsdk/buildenv.mk` as a part of SGX SDK. However, the SGX SDK is not installed in the base image `Ubuntu:22.04`. 

I think the builder phase installs SGX SDK should be done before building the dependent library.

**Comment by lingyuj** [comment]
This is a known bug and we will submit a PR very soon. Thank you for reporting the issue.

**Comment by lingyuj** [comment]
The PR has been merged:
https://github.com/intel/SGXDataCenterAttestationPrimitives/pull/354
