### ISSUE TITLE
SGX2 support in Linux driver

### ISSUE THREAD

**Issue by 0xabu** [intel/SGXDataCenterAttestationPrimitives#37]
Are there any plans or guidance to build a Linux driver with support for both SGX2 (EDMM) and the DCAP LE?

This is especially relevant since https://github.com/intel/linux-sgx-driver/pull/92 deprecated the master branch of linux-sgx-driver, and this project contains what's apparently a fork of that codebase.

**Comment by haitaohuang** [comment]
linux-sgx-driver still support sgx2 in . This driver follows closely with upstreaming kernel patches and can be used before upstreaming is done. For that purpose, sgx2 won't be supported in this driver.
Plus, please note linux-sgx-driver SGX2 related interfaces may/will not be identical to final upstream version in kernel.

**Comment by 0xabu** [comment]
In case anyone else finds this useful: https://github.com/0xabu/linux-sgx-driver/tree/sgx2_dcap
