### ISSUE TITLE
QuoteProvider Sample removed?

### ISSUE THREAD

**Issue by jmechalas** [intel/SGXDataCenterAttestationPrimitives#38]
The 1.2 release no longer has the QuoteProviderSample code in the SampleCode directory. Is there a reason why this was removed?

**Comment by andyzyb** [comment]
As we provided quote provider library in the latest release, this sample code seems no longer necessary.

**Comment by jmechalas** [comment]
Thanks! I hadn't noticed the change. I overlooked the README and was just looking at the directory contents which didn't appear to have changed much.
