### ISSUE TITLE
PCCS installation failed

### ISSUE THREAD

**Issue by wgn1993** [intel/SGXDataCenterAttestationPrimitives#392]
hi,
I tried to install PCCS via source code/Debian package/APT,  with the correct nodejs version indicated(>18), I have tried multiple ways but the installation all failed with compiled error which is as follow:
![屏幕截图 2024-04-18 173343](https://github.com/intel/SGXDataCenterAttestationPrimitives/assets/15976364/8e830c57-75e1-4a8f-a0e0-a59a438ffb58)
Any thoughts on that?

**Comment by BigThor12** [comment]
Hi, i had the same issue. This one #390 solved the problem in my case

**Comment by anjalirai-intel** [comment]
we have also faced issues related to pccs installation and raised them to linux-sgx team [1029](https://github.com/intel/linux-sgx/issues/1029)

**Comment by lingyuj** [comment]
> we have also faced issues related to pccs installation and raised them to linux-sgx team [1029](https://github.com/intel/linux-sgx/issues/1029)

Please check the solution in this thread: https://github.com/intel/SGXDataCenterAttestationPrimitives/issues/390

**Comment by anjalirai-intel** [comment]
> > we have also faced issues related to pccs installation and raised them to linux-sgx team [1029](https://github.com/intel/linux-sgx/issues/1029)
> 
> Please check the solution in this thread: #390

@lingyuj We already resolved on our own. But the docs should be updated. It is still the same procedure

**Comment by lingyuj** [comment]
> > > we have also faced issues related to pccs installation and raised them to linux-sgx team [1029](https://github.com/intel/linux-sgx/issues/1029)
> > 
> > 
> > Please check the solution in this thread: #390
> 
> @lingyuj We already resolved on our own. But the docs should be updated. It is still the same procedure

Thanks for reporting the issue. We were aware of this and had updated the related docs in the last release. And the code will be updated in the next release to support all major node.js versions.

**Comment by wgn1993** [comment]
> Hi, i had the same issue. This one #390 solved the problem in my case. Seems like only certain nodejs version can run PCCS

Thanks!! It works now without issue.
