### ISSUE TITLE
关于编译PCKCertSelectionLib失败的问题

### ISSUE THREAD

**Issue by Handikang** [intel/SGXDataCenterAttestationPrimitives#396]
按照pccs的部署要求，我看了linux手动安装的教程，前置条件是需要先编译PCKCertSelectionLib，但是我发现编译出现了错误，我已经安装好了intel sgx sdk和psw和driver,我很困惑
![image](https://github.com/intel/SGXDataCenterAttestationPrimitives/assets/42713276/f082cac0-5171-4efe-9360-4efef3d26b21)

**Comment by dashuaic** [comment]
You didn't download all the source code, there are some submodules. You need to update all submodule code (there may be nested submodules).
