### ISSUE TITLE
SGX DCAP for Ubuntu22

### ISSUE THREAD

**Issue by HazyMrf** [intel/SGXDataCenterAttestationPrimitives#400]
I'm trying to use IntelSGX on my Ubuntu22 and according to https://github.com/intel/linux-sgx I can do that, but as DCAP readme.md for quote generation/verification says, the latest available version is Ubuntu20. So is there a way to use SGX with DCAP on my Ubuntu22 or should I downgrade it?

**Comment by lingyuj** [comment]
You can use Ubuntu 22. Please check the installation guide here: 
https://download.01.org/intel-sgx/sgx-dcap/1.8/linux/docs/Intel_SGX_DCAP_Linux_SW_Installation_Guide.pdf

**Comment by lingyuj** [comment]
> I'm trying to use IntelSGX on my Ubuntu22 and according to https://github.com/intel/linux-sgx I can do that, but as DCAP readme.md for quote generation/verification says, the latest available version is Ubuntu20. So is there a way to use SGX with DCAP on my Ubuntu22 or should I downgrade it?

You can use Ubuntu 22. See installation guide for Linux here:
https://download.01.org/intel-sgx/sgx-dcap/1.21/linux/docs/Intel_SGX_SW_Installation_Guide_for_Linux.pdf

**Comment by HazyMrf** [comment]
So it appears that readme is outdated... Thank you for such a quick response!
