### ISSUE TITLE
Wrong API definition in Rust version

### ISSUE THREAD

**Issue by Xynnn007** [intel/SGXDataCenterAttestationPrimitives#404]
Hi, when I use `get_report()` api defined [here](https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/main/QuoteGeneration/quote_wrapper/tdx-attest-rs/src/lib.rs#L162-L171) of rust version. I set the parameter `tdx_report_data` to `None` as it is an `Option`.

But the program panics. When I dived into this, I found that the call stack
- https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/45554a754ba8c03342cc394831fa7f04db08805c/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L831-L833
- https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/45554a754ba8c03342cc394831fa7f04db08805c/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L844
- https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/45554a754ba8c03342cc394831fa7f04db08805c/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L194-L198
- and finally here https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/45554a754ba8c03342cc394831fa7f04db08805c/QuoteGeneration/quote_wrapper/tdx_attest/tdx_attest.c#L206-L209

The last line asserts that the report data pointer should not be none.

So the outer API of rust version is somehow misleading, hinting that it could be a None (nullptr in underlying C).

Some suggestions:
- Change the outer API
- Add some logic to make a report_data with all `\0` in the inner logic if given `None`, and still leave the outer API parameter `Option`

**Comment by llly** [comment]
Thanks. Changing the outer API is better since Rust API is wrapper of C API.

**Comment by Xynnn007** [comment]
> Thanks. Changing the outer API is better since Rust API is wrapper of C API.

Yes. From a point of view of a caller of downstream, I prefer way 2 as it provides flexibility. Just fyi

**Comment by Xynnn007** [comment]
> Thanks. Changing the outer API is better since Rust API is wrapper of C API.

Yes. From a point of view of a caller of downstream, I prefer way 2 as it provides flexibility. Just fyi

**Comment by llly** [comment]
> > Thanks. Changing the outer API is better since Rust API is wrapper of C API.
> 
> Yes. From a point of view of a caller of downstream, I prefer way 2 as it provides flexibility. Just fyi

OK. Will create a PR to fix it.
