### ISSUE TITLE
Update nodejs version pinning to latest

### ISSUE THREAD

**Issue by JakubLedworowski** [intel/SGXDataCenterAttestationPrimitives#405]
Currently there is no way to install DCAP PCCS using package manager, because installation is pinned to old nodejs versions. The DCAP PCCS installation is not accepted for the latest nodejs version.

I am referring to this code:
https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/DCAP_1.21/QuoteGeneration/pccs/package-lock.json#L32

Here is the list of latest nodejs releases:
https://nodejs.org/en/about/previous-releases#looking-for-latest-release-of-a-version-branch

For node 18 - v18.20.3
For node 20 - v20.13.1
For node 21 - v21.7.3

Please either update nodejs version pinning to latest or remove the upper bound, which will help improve user experience.

**Comment by JakubLedworowski** [comment]
Hi, let me bump this issue.

**Comment by lingyuj** [comment]
We will have a new solution to fix the issue in the future releases.
Meanwhile, please check this wiki page for how to install a specific version of Node.js:
https://github.com/nodesource/distributions/wiki/How-to-select-the-Node.js-version-to-install
