### ISSUE TITLE
the prebuild quote provider library .deb CANNOT BE INSTALLED on ubuntu 18.04

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#45]
Hi,
I encountered the following issue, could sgx team help to look at this? It seems a blocking issue.

sgx@sgx-HP-EliteDesk-800-G4-WKS-TWR:~/Downloads$ sudo dpkg -i libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb
(Reading database ... 184189 files and directories currently installed.)
Preparing to unpack libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb ...
Unpacking libsgx-dcap-default-qpl (1.2.100.51313-bionic1) ...
dpkg: error processing archive libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb (--install):
 trying to overwrite '/etc/sgx_default_qcnl.conf', which is also in package libsgx-enclave-common 2.6.100.51285-bionic1
Processing triggers for libc-bin (2.27-3ubuntu1) ...
Errors were encountered while processing:
 libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb

Thanks,
Su

**Comment by wangsu502** [comment]
well, found a workaround, using -force-overwrite option.

sgx@sgx-HP-EliteDesk-800-G4-WKS-TWR:~/Downloads$ sudo dpkg -i --force-overwrite  libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb 
(Reading database ... 184194 files and directories currently installed.)
Preparing to unpack libsgx-dcap-default-qpl_1.2.100.51313-bionic1_amd64.deb ...
Unpacking libsgx-dcap-default-qpl (1.2.100.51313-bionic1) ...
dpkg: warning: overriding problem because --force enabled:
dpkg: warning: trying to overwrite '/etc/sgx_default_qcnl.conf', which is also in package libsgx-enclave-common 2.6.100.51285-bionic1
Setting up libsgx-dcap-default-qpl (1.2.100.51313-bionic1) ...
Processing triggers for libc-bin (2.27-3ubuntu1) ...

**Comment by lzha101** [comment]
The libsgx_enclave_common package has been updated in dcap-1.2 folder on download.01.org.  You can try to uninstall the existing version 2.6.100.51285 and install the updated version.

**Comment by wangsu502** [comment]
thanks, @lzha101
