### ISSUE TITLE
potential memory leak in se_map.c

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#50]
map_handle_t* map_file(se_file_handle_t file, uint32_t *size)
{
    map_handle_t* mh = (map_handle_t *)calloc(1, sizeof(map_handle_t));
    if (mh == NULL || size == NULL)
        return NULL;  // FIXME

    // Using GetFileSizeEx instead of GetFileSize.
    // We do NOT support mapping files larger than max uint32_t with this API.
    LARGE_INTEGER file_size; file_size.QuadPart = 0;
    if (GetFileSizeEx(file, &file_size) && file_size.HighPart == 0)
    {
        *size = file_size.LowPart;
    }
    else
    {
        return NULL;  // FIXME
    }

**Comment by llly** [comment]
fixed in PR #51
