### ISSUE TITLE
QVE sample code doesn't work

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#52]
Hi,
I could confirm PCCS and other dependencies have been installed and work (QL sample code could work). But I can't make the folllowing test passed.  
sgx@sgx-test:~/SGXDataCenterAttestationPrimitives/QuoteVerification/SampleISVEnclave$ ./app 
Info: get target info successfully returned.
Info: sgx_qv_set_enclave_load_policy successfully returned.
Info: sgx_qv_get_quote_supplemental_data_size successfully returned.
Error: App: sgx_qv_verify_quote failed: 0xe01b
Error: failed to verify QvE report. 0x3001
Error: App: Verification completed with Terminal result: e006
Enter a character before exit ...

**Comment by akryeem-INTC** [comment]
Hi,
The error you're getting `0xe01b` maps to: SGX_QL_NO_QUOTE_COLLATERAL_DATA.
That means there is no matching data in Intel's server for the machine you're using to generate the quote.
What machine/CPU, FMSPc are you using?

**Comment by wangsu502** [comment]
> Hi,
> The error you're getting `0xe01b` maps to: SGX_QL_NO_QUOTE_COLLATERAL_DATA.
> That means there is no matching data in Intel's server for the machine you're using to generate the quote.
> What machine/CPU, FMSPc are you using?

Hi akryeem,
it's NUC7C with the intel specified bios version for dcap.

**Comment by wangsu502** [comment]
:100: 
thank you for your reply
