### ISSUE TITLE
1.3.1 build failure

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#57]
scripts/installConfig
~/SGXDataCenterAttestationPrimitives/QuoteGeneration
~/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3 ~/SGXDataCenterAttestationPrimitives/QuoteGeneration
~/SGXDataCenterAttestationPrimitives/QuoteGeneration
~/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3 ~/SGXDataCenterAttestationPrimitives/QuoteGeneration
~/SGXDataCenterAttestationPrimitives/QuoteGeneration
~/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3 ~/SGXDataCenterAttestationPrimitives/QuoteGeneration
dpkg-buildpackage: info: 源码包 libsgx-dcap-ql
dpkg-buildpackage: info: 源码版本 1.3.101.3-bionic1
dpkg-buildpackage: info: source distribution unstable
dpkg-buildpackage: info: 源码修改者 Xiangquan Liu <xiangquan.liu@intel.com>
dpkg-buildpackage: info: 主机架构 amd64
 dpkg-source --before-build libsgx-dcap-ql-1.3.101.3
 fakeroot debian/rules clean
make[2]: 进入目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
dh clean
   dh_auto_clean
   dh_clean
make[2]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
 dpkg-source -b libsgx-dcap-ql-1.3.101.3
dpkg-source: info: using source format '3.0 (quilt)'
dpkg-source: info: building libsgx-dcap-ql using existing ./libsgx-dcap-ql_1.3.101.3.orig.tar.gz
dpkg-source: info: building libsgx-dcap-ql in libsgx-dcap-ql_1.3.101.3-bionic1.debian.tar.xz
dpkg-source: info: building libsgx-dcap-ql in libsgx-dcap-ql_1.3.101.3-bionic1.dsc
 debian/rules build
make[2]: 进入目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
dh build
   dh_update_autotools_config
   dh_auto_configure
   dh_auto_build
	make -j1
make[3]: 进入目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
make[3]: 对“default”无需做任何事。
make[3]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
   dh_auto_test
make[2]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
 fakeroot debian/rules binary
make[2]: 进入目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
dh binary
   dh_testroot
   dh_prep
   dh_auto_install
	make -j1 install DESTDIR=/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3/debian/libsgx-dcap-ql AM_UPDATE_INFO_DIR=no
make[3]: 进入目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
install -d /home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3/debian/libsgx-dcap-ql/usr/lib/x86_64-linux-gnu
install package/lib/* /home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3/debian/libsgx-dcap-ql/usr/lib/x86_64-linux-gnu
install: 无法获取'package/lib/*' 的文件状态(stat): 没有那个文件或目录
Makefile:43: recipe for target 'install' failed
make[3]: *** [install] Error 1
make[3]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
dh_auto_install: make -j1 install DESTDIR=/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3/debian/libsgx-dcap-ql AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:8: recipe for target 'binary' failed
make[2]: *** [binary] Error 2
make[2]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration/installer/linux/deb/libsgx-dcap-ql/libsgx-dcap-ql-1.3.101.3”
dpkg-buildpackage: 错误: fakeroot debian/rules binary subprocess returned exit status 2
Makefile:88: recipe for target 'deb_sgx_dcap_ql_pkg' failed
make[1]: *** [deb_sgx_dcap_ql_pkg] Error 2
make[1]: 离开目录“/home/wangsu/SGXDataCenterAttestationPrimitives/QuoteGeneration”
Makefile:37: recipe for target 'all' failed
make: *** [all] Error 2

And I checked this config:
cat ./QuoteGeneration/installer/linux/common/libsgx-dcap-ql/output/scripts/installConfig

NGA_VERSION="1.0"
TARBALL_NAME=libsgx-dcap-ql_1.0.orig.tar.gz
NGA_PKG_NAME=libsgx-dcap-ql

LIB_DIR=lib

**Comment by llly** [comment]
It seems that the failure is  related to non-English OS.  We will fix it if it is confirmed a bug.

**Comment by wangsu502** [comment]
> It seems that the failure is related to non-English OS. We will fix it if it is confirmed a bug.

thank you for your timely response, Xun

**Comment by llly** [comment]
fixed at #58
