### ISSUE TITLE
Get an error 0xe035 when executing QuoteGenerationSample

### ISSUE THREAD

**Issue by RMheng** [intel/SGXDataCenterAttestationPrimitives#62]
Hi,
I  try to executing the SampleCode,but get an error.

Step1: Call sgx_qe_get_target_info:Error in sgx_qe_get_target_info. 0xe035

0x0035 means that SGX_QL_ERROR_INVALID_PRIVILEGE,and says that no enough privilege to perform the operation.
I tried to make with DEBUG=1,but no else information output.
I wonders that how to solving this problem?Thanks for your time!!

**Comment by andyzyb** [comment]
Please check your environment first
1.  Is your system supporting Flexible Launch Control?
2.  Did you install DCAP driver in your system, any error/message you've during driver installation?

**Comment by RMheng** [comment]
> Please check your environment first
> 
> 1. Is your system supporting Flexible Launch Control?
> 2. Did you install DCAP driver in your system, any error/message you've seen during driver installation?


Thanks for your timely response!!!
I checked and found that I didn't install DCAP driver correctly.
During the installation procedure of DCAP driver, I wondered whether the README not updated in time?Becase the LE folder has been moved.

**Comment by andyzyb** [comment]
Thanks for the reminder,  README needs to be updated.  At present, you can use the driver installer instead of building it yourself.  

https://download.01.org/intel-sgx/sgx-dcap/1.3.1/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.20.bin

**Comment by RMheng** [comment]
> Thanks for the reminder, README needs to be updated. At present, you can use the driver installer instead of building it yourself.
> 
> https://download.01.org/intel-sgx/sgx-dcap/1.3.1/linux/distro/ubuntuServer18.04/sgx_linux_x64_driver_1.20.bin

Thanks for your help！I think the issue can be closed.
