### ISSUE TITLE
How to figure out the exact cause of  `SGX_QL_TCBINFO_UNSUPPORTED_FORMAT` error

### ISSUE THREAD

**Issue by sammyne** [intel/SGXDataCenterAttestationPrimitives#85]
Hi~

I'm playing with dcap-v1.3 recently, and write toy project as https://github.com/sammyne/sgx-dcap-playground. It has run ok before. But recently, `SGX_QL_TCBINFO_UNSUPPORTED_FORMAT` error pops out, and I cannot figure out why?

My environment goes as 
- ubuntu 16.04
- SGX v2.7
- DCAP v1.3.101.3

The project is very simple and based on teaclave-sgx-sdk. 

It would be also nice if someone could also tell me how to enable the tracing log such as https://github.com/intel/SGXDataCenterAttestationPrimitives/blob/DCAP_1.3.1/QuoteVerification/dcap_quoteverify/sgx_dcap_quoteverify.cpp#L333, which helps me debugging during native development~

Really appreciate if someone could help me out~

**Comment by hyjiang** [comment]
Several failures would cause SGX_QL_TCBINFO_UNSUPPORTED_FORMAT, but maybe you need to check below 2 items first.

- Some fields in TCBInfo.json has been changed, then QVL can NOT parse the JSON file
- The TCB version is NOT correct, only version 2 and 3 are supported

Regarding the trace log, you can update dcap_quoteverify Makefile to add  "-DSE_DEBUG_LEVEL=SE_TRACE_DEBUG -DDEBUG_MODE=1" to enable internal log. 
We will add such support in next release.

**Comment by sammyne** [comment]
Many thanks~ @hyjiang
