### ISSUE TITLE
[build fails]: `Please decompress prebuilt enclave package before compiling`

### ISSUE THREAD

**Issue by niklasad1** [intel/SGXDataCenterAttestationPrimitives#87]
Hey, I tried to build the library by `$ make` in the root but it fails with: 

`ERROR: Please decompress prebuilt enclave package before compiling.
Exiting......
`

I have no idea how to decompress `the prebuilt`, can somebody clarify or help me please?

**Comment by andyzyb** [comment]
Please follow the steps in readme.

```
Use the script to download prebuilt binaries to prebuilt folder:
    download_prebuilt.bat
```

**Comment by niklasad1** [comment]
Thanks, easy to miss that step when one runs `make` from the root though.
