### ISSUE TITLE
Unsuccessful debug build 

### ISSUE THREAD

**Issue by yufjiang** [intel/SGXDataCenterAttestationPrimitives#89]
I am trying build Quote Generation Library. 

With all prerequisite installed, my normal build by running "make" works well.

But when I try to build debug libraries by running "make DEBUG=1". I am keeping running into the issue below:

../qe_logic.cpp: In function ‘void* get_qpl_handle()’:
../qe_logic.cpp:259:13: error: ‘old_libname_used’ was not declared in this scope
             old_libname_used = true;
             ^~~~~~~~~~~~~~~~
Makefile:87: recipe for target '../qe_logic.o' failed
make[2]: *** [../qe_logic.o] Error 1
make[2]: Leaving directory '/home/yufjiang/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/quote/linux'
Makefile:90: recipe for target '../../quote/linux/libsgx_qe3_logic.so' failed
make[1]: *** [../../quote/linux/libsgx_qe3_logic.so] Error 2
make[1]: Leaving directory '/home/yufjiang/SGXDataCenterAttestationPrimitives/QuoteGeneration/quote_wrapper/ql/linux'
Makefile:55: recipe for target 'qe3_logic' failed
make: *** [qe3_logic] Error 2

Please let me know if there are any workaround. Thank you very much!

**Comment by yufjiang** [comment]
Transient. Closed the issue.

**Comment by andyzyb** [comment]
Thanks for reporting the issue.  Debug build is broken and will fix it soon.

**Comment by andyzyb** [comment]
@yufjiang , please pull the latest code and try again.

**Comment by yufjiang** [comment]
> @yufjiang , please pull the latest code and try again.

@andyzyb Thanks for your prompt help! I can do the debug build successfully with the latest master branch now. Feel free to close the issue. Really appreciate the fix.
