### ISSUE TITLE
SampleCode/QuoteGenerationSample  build failure

### ISSUE THREAD

**Issue by wangsu502** [intel/SGXDataCenterAttestationPrimitives#91]
SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample/Makefile should be fixed.

diff --git a/SampleCode/QuoteGenerationSample/Makefile b/SampleCode/QuoteGenerationSample/Makefile
index f77f413..0036bee 100644
--- a/SampleCode/QuoteGenerationSample/Makefile
+++ b/SampleCode/QuoteGenerationSample/Makefile
@@ -77,7 +77,7 @@ else ifeq ($(IS_RHEL),)
 endif
 
 App_Cpp_Flags := $(App_C_Flags) -std=c++11
-App_Link_Flags := $(SGX_COMMON_CFLAGS) -l$(DCAP_Library_Name) -l$(Urts_Library_Name) -l$(Uae_Library_Name) -ldl -lpthread 
+App_Link_Flags := $(SGX_COMMON_CFLAGS) -L$(SGX_LIBRARY_PATH) -l$(DCAP_Library_Name) -l$(Urts_Library_Name) -l$(Uae_Library_Name) -ldl -lpthread 

Below is error log:
nuc@nuc:~/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample$ make
make target
make[1]: 进入目录“/home/nuc/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample”
cd App && /opt/intel/sgxsdk/bin/x64/sgx_edger8r --untrusted ../Enclave/Enclave.edl
GEN  =>  App/Enclave_u.c
CC   <=  App/Enclave_u.c
CXX  <=  App/App.cpp
g++ App/Enclave_u.o App/App.o -o app -m64 -O2 -lsgx_dcap_ql -lsgx_urts -lsgx_quote_ex -ldl -lpthread 
/usr/bin/ld: 找不到 -lsgx_quote_ex
collect2: error: ld returned 1 exit status
Makefile:178: recipe for target 'app' failed
make[1]: *** [app] Error 1
make[1]: 离开目录“/home/nuc/SGXDataCenterAttestationPrimitives/SampleCode/QuoteGenerationSample”
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by fqiu1** [comment]
You need to install libsgx-qutoe-ex-dev package.

**Comment by wangsu502** [comment]
> You need to install libsgx-qutoe-ex-dev package.

it's been installed

**Comment by fqiu1** [comment]
Which distribution are you using? If it is ubuntu, please paste the output of "dpkg -L libsgx-quote-ex-dev“

**Comment by wangsu502** [comment]
> dpkg -L libsgx-quote-ex-dev

$ dpkg -L libsgx-quote-ex-dev
/.
/usr
/usr/include
/usr/include/sgx_uae_quote_ex.h
/usr/lib
/usr/lib/x86_64-linux-gnu
/usr/share
/usr/share/doc
/usr/share/doc/libsgx-quote-ex-dev
/usr/share/doc/libsgx-quote-ex-dev/changelog.Debian.gz
/usr/share/doc/libsgx-quote-ex-dev/copyright
/usr/lib/x86_64-linux-gnu/libsgx_quote_ex.so

It's Ubuntu1804

**Comment by wangsu502** [comment]
anyway, libsgx-quote-ex-dev is not mentioned in the dcap installation guide

**Comment by fqiu1** [comment]
It seems /usr/lib/x86_64-linux-gnu/libsgx_quote_ex.so is in your system library path, but you still cannot pass build?

**Comment by wangsu502** [comment]
yes, it's wired

**Comment by hyjiang** [comment]
Suppose /usr/lib/x86_64-linux-gnu/libsgx_quote_ex.so should link to libsgx_quote_ex.so.1.1.105.1 (or other version), pls help to check. 

lrwxrwxrwx 1 root root      28 3月  23 17:01 libsgx_quote_ex.so.1 -> libsgx_quote_ex.so.1.1.105.1
-rw-r--r-- 1 root root  276512 3月  23 17:01 libsgx_quote_ex.so.1.1.105.1
