### ISSUE TITLE
[Driver 1.32] Why is X86_FEATURE_TPR_SHADOW being used as a proxy for SGX1 support?

### ISSUE THREAD

**Issue by jhand2** [intel/SGXDataCenterAttestationPrimitives#95]
SInce the 1.32 release in `driver/linux/main.c`, the driver checks for SGX1 support:

```
if (!cpu_has(c, X86_FEATURE_SGX1)) {
    pr_err_once("sgx: SGX1 instruction set is not supported\n");
    return false;
}
```

in drvier/linux/include/dcap.h I see `X86_FEATURE_SGX1` is defined as:

```
#define X86_FEATURE_SGX1         ( 8*32+ 0) /* SGX1 leaf functions */
```

But in the Linux kernel source (arch/x86/include/asm/cpufeatures.h) I see:

```
#define X86_FEATURE_TPR_SHADOW		( 8*32+ 0) /* Intel TPR Shadow */
```

So it would appear X86_FEATURE_TPR_SHADOW is being used by the dcap driver as a proxy for SGX1 support. Is this intentional? On some machines this bit is not set (but the X86_FEATURE_SGX bit IS set) which causes the driver to fail to load.

**Comment by jhand2** [comment]
Note that the previous DCAP driver (1.22) checked for X86_FEATURE_SGX, which should be set by CPUID.

I have confirmed that if I change the above check to the following, everything works.

```
if (!cpu_has(c, X86_FEATURE_SGX)) {
    pr_err_once("sgx: SGX1 instruction set is not supported\n");
    return false;
}
```

I'm happy to submit a PR

**Comment by haitaohuang** [comment]
Which version of kernel are you using?
There was a patch series merged into kernl 5.6 which re-organized the feature macros.

**Comment by jhand2** [comment]
@haitaohuang I have tested on 4.15 (default Ubuntu kernel). I'll take a look at the latest source.

What kernels is this version of the driver expected to work with?

**Comment by jhand2** [comment]
In the latest pull of master from https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git I still see

`#define X86_FEATURE_TPR_SHADOW		( 8*32+ 0) /* Intel TPR Shadow */``

**Comment by jhand2** [comment]
In v28 of the upstream driver I do see:

`#define X86_FEATURE_SGX1		(19*32+ 0) /* SGX1 leaf functions */`

Was the intention to use that define?

**Comment by haitaohuang** [comment]
yeah, it's likely given the history of the sgx patches :-)

**Comment by jhand2** [comment]
Although I tried changing to `#define X86_FEATURE_SGX1 (19*32+ 0) /* SGX1 leaf functions */` and it still doesn't seem to work on my test machine. I would have to look through the upstream driver to see if is explicitly set somewhere or if it's implicit from CPUID.

**Comment by haitaohuang** [comment]
this patch series re-org the feature bits: https://patchwork.kernel.org/patch/11306675/
I think it is not the implicit cpuid

**Comment by jhand2** [comment]
What is the support matrix for the dcap driver? That is, how many kernels back is it supposed to support?

I have tested that my PR (#96) works properly on Ubuntu 16.04 with the Ubuntu Azure kernel 4.15.

**Comment by haitaohuang** [comment]
Thanks. This should be good enough for now. Once we have newer kernel supporting detect for SGX1 and SGX2 we can add back

**Comment by jhand2** [comment]
Ok sounds good. Feel free to close or keep open for tracking
