### ISSUE TITLE
The configurations of pccs cannot be done by using Linux Debian package installer

### ISSUE THREAD

**Issue by yufjiang** [intel/SGXDataCenterAttestationPrimitives#98]
In the document: https://github.com/intel/SGXDataCenterAttestationPrimitives/tree/master/QuoteGeneration/pccs
![image](https://user-images.githubusercontent.com/58716052/79815032-8cae6980-8334-11ea-8162-582132939558.png)
It was mentioned that "All configurations can be done during the installation process." 

But when I run 
dpkg -i libsgx-dcap-pccs_1.3.100.4-bionic1_amd64.deb
It installed the files into their destination folders, but didn't prompt any configuration process. 
Do I miss anything here?

The manual installation works well for me though. 

Thanks for your help!

**Comment by lingyuj** [comment]
Hi Yufei,
The instruction only applies to the latest pccs debian package, which I think should be sgx-dcap-pccs_1.6.100.2-xenial1_amd64.deb
You can find more information at https://01.org/intel-software-guard-extensions/downloads

**Comment by yufjiang** [comment]
Thanks for clarification!
